/**
 * GENERATED FILE — do not edit by hand.
 *
 * Written by `npm run catalogue:build` from the ATU knowledge base's
 * license-filtered export. Every entry here survived, in order:
 *
 *   1. the stem screen in `lib/safety.ts` applied to its canonical title;
 *   2. having any motif data at all (no data means no way to check, which is
 *      treated as a rejection, not a pass);
 *   3. carrying no motif with a knowledge-base content advisory;
 *   4. the same stem screen applied to every one of its motif labels.
 *
 * Titles are the canonical scholarly titles from the knowledge base, carried
 * verbatim — unlike the hand-authored tiers, nothing here is retitled for
 * children, because nobody has read these tales to retitle them honestly.
 *
 * `blurb` is present only where `data/atu-blurbs.reviewed.json` supplies a
 * reviewed one. Most entries have none, and the catalogue shows the ATU number
 * and division instead of inventing a description.
 *
 * These tale types are offered but not vouched for the way the featured ones
 * are. What keeps a story from them gentle is `SYSTEM_PROMPT` in
 * `lib/prompt.ts`, which applies to every tale regardless of type.
 */

export interface AtuExtendedEntry {
  id: string;
  atu: string;
  title: string;
  emoji: string;
  blurb?: string;
}

/** 254 generated tale types, in ATU order. */
export const ATU_EXTENDED: readonly AtuExtendedEntry[] = [
  { id: "atu-2b-basket-tied-to-wolf-s-tail", atu: "2B", title: "Basket tied to Wolf's Tail", emoji: "🦊" },
  { id: "atu-5-biting-the-tree-root", atu: "5", title: "Biting the Tree Root", emoji: "🐭" },
  { id: "atu-6-animal-captor-persuaded-to-talk", atu: "6", title: "Animal Captor Persuaded to Talk", emoji: "🦁" },
  { id: "atu-6-animal-captor-talks-with-booty-in", atu: "6*", title: "Animal Captor Talks with Booty in His Mouth", emoji: "🐦" },
  { id: "atu-7-the-three-tree-names", atu: "7", title: "The Three Tree Names", emoji: "🐢" },
  { id: "atu-20c-the-animals-flee-in-fear-of", atu: "20C", title: "The Animals Flee in Fear of the End of the World", emoji: "🐭" },
  { id: "atu-31-fox-climbs-from-the-pit-on", atu: "31", title: "Fox Climbs from the Pit on the Wolf's Back", emoji: "🦁" },
  { id: "atu-32-the-wolf-descends-into-the-well", atu: "32", title: "The Wolf Descends into the Well in One Bucket and Rescues the Fox in the Other", emoji: "🐢" },
  { id: "atu-34-the-wolf-dives-into-the-water", atu: "34", title: "The Wolf Dives into the Water for Reflected Cheese", emoji: "🐻" },
  { id: "atu-34a-the-dog-drops-his-meat-for", atu: "34A", title: "The Dog Drops His Meat for the Reflection", emoji: "🦊" },
  { id: "atu-34c-the-monkey-with-the-lentils", atu: "34C", title: "The Monkey with the Lentils", emoji: "🐺" },
  { id: "atu-35b-the-fox-gets-bait-from-trap", atu: "35B*", title: "The Fox Gets Bait from Trap by Luring Wolf into It", emoji: "🐺" },
  { id: "atu-41-the-wolf-overeats-in-the-cellar", atu: "41", title: "The Wolf Overeats in the Cellar", emoji: "🐭" },
  { id: "atu-43-the-bear-builds-a-house-of", atu: "43", title: "The Bear Builds a House of Wood; the Fox, of Ice", emoji: "🐢" },
  { id: "atu-50a-fox-sees-all-tracks-going-into", atu: "50A", title: "Fox Sees all Tracks going into Lion's Den but none coming out", emoji: "🦁" },
  { id: "atu-51a-the-fox-has-the-sniffles", atu: "51A", title: "The Fox Has the Sniffles", emoji: "🐭" },
  { id: "atu-53-the-fox-investigates-a-roar", atu: "53*", title: "The Fox Investigates a Roar", emoji: "🐦" },
  { id: "atu-58-the-crocodile-carries-the-jackal", atu: "58", title: "The Crocodile Carries the Jackal", emoji: "🐰" },
  { id: "atu-63-the-fox-rids-himself-of-fleas", atu: "63", title: "The Fox Rids himself of Fleas", emoji: "🐭" },
  { id: "atu-67-the-fox-in-a-swollen-river", atu: "67", title: "The Fox in a Swollen River", emoji: "🐻" },
  { id: "atu-67-the-fox-caught-by-butcher", atu: "67**", title: "The Fox Caught by Butcher", emoji: "🐻" },
  { id: "atu-75-the-help-of-the-weak", atu: "75", title: "The Help of the Weak", emoji: "🦁" },
  { id: "atu-75-the-wolf-and-the-nurse", atu: "75*", title: "The Wolf and the Nurse (previously Wolf Waits in Vain for the Nurse to Throw away the Child)", emoji: "🐦" },
  { id: "atu-75a-the-lion-and-the-worm", atu: "75A", title: "The Lion and the Worm", emoji: "🐰" },
  { id: "atu-78a-animal-tied-up-because-of-a", atu: "78A", title: "Animal Tied Up Because of a Storm", emoji: "🦊" },
  { id: "atu-80a-who-gets-the-booty", atu: "80A*", title: "Who Gets the Booty?", emoji: "🐻" },
  { id: "atu-81-too-cold-for-hare-to-build", atu: "81", title: "Too Cold for Hare to Build House in Winter", emoji: "🐻" },
  { id: "atu-87a-the-bear-stands-on-a-heap", atu: "87A*", title: "The Bear Stands on a Heap of Wood", emoji: "🦊" },
  { id: "atu-93-the-master-taken-seriously", atu: "93", title: "The Master Taken Seriously", emoji: "🐺" },
  { id: "atu-107-struggle-between-dogs-and-wolves", atu: "107", title: "Struggle between Dogs and Wolves", emoji: "🦊" },
  { id: "atu-111-the-cat-and-the-mouse-converse", atu: "111", title: "The Cat and the Mouse Converse", emoji: "🐻" },
  { id: "atu-112-the-mice-and-the-rooster", atu: "112**", title: "The Mice and the Rooster", emoji: "🐺" },
  { id: "atu-116-the-bear-on-the-hay-wagon", atu: "116", title: "The Bear on the Hay-Wagon", emoji: "🦁" },
  { id: "atu-120-the-first-to-see-the-sunrise", atu: "120", title: "The First to See the Sunrise", emoji: "🐢" },
  { id: "atu-121-wolves-climb-on-top-of-one", atu: "121", title: "Wolves Climb on Top of One Another", emoji: "🦊" },
  { id: "atu-122c-the-sheep-persuades-the-wolf-to", atu: "122C", title: "The Sheep Persuades the Wolf to Sing", emoji: "🐺" },
  { id: "atu-122d-caught-animal-promises-captor-better-prey", atu: "122D", title: "Caught Animal Promises Captor Better Prey", emoji: "🐰" },
  { id: "atu-122e-wait-for-the-fat-goat", atu: "122E", title: "Wait for the Fat Goat", emoji: "🐦" },
  { id: "atu-135-the-mouse-makes-a-boat-of", atu: "135*", title: "The Mouse Makes a Boat of a Bread-Crust", emoji: "🐢" },
  { id: "atu-135a-the-fox-stumbles-over-a-violin", atu: "135A*", title: "The Fox Stumbles over a Violin", emoji: "🐦" },
  { id: "atu-136a-confession-of-animals", atu: "136A*", title: "Confession of Animals", emoji: "🐭" },
  { id: "atu-152-the-plowman-and-the-animals", atu: "152", title: "The Plowman and the Animals", emoji: "🦁" },
  { id: "atu-156a-the-faith-of-the-lion", atu: "156A", title: "The Faith of the Lion", emoji: "🐢" },
  { id: "atu-157b-the-sparrow-and-his-sons", atu: "157B", title: "The Sparrow and His Sons", emoji: "🐢" },
  { id: "atu-158-the-wild-animals-on-the-sleigh", atu: "158", title: "The Wild Animals on the Sleigh", emoji: "🐦" },
  { id: "atu-159-straw-bull", atu: "159", title: "Straw Bull", emoji: "🐭" },
  { id: "atu-159-quarrel-over-the-stag", atu: "159*", title: "Quarrel over the Stag", emoji: "🐭" },
  { id: "atu-159c-the-lion-and-the-statue", atu: "159C", title: "The Lion and the Statue", emoji: "🦁" },
  { id: "atu-162-the-master-looks-more-closely-than", atu: "162", title: "The Master Looks More Closely than the Farmhand", emoji: "🐭" },
  { id: "atu-163-the-singing-wolf", atu: "163", title: "The Singing Wolf", emoji: "🦁" },
  { id: "atu-168a-the-old-woman-and-the-wolf", atu: "168A", title: "The Old Woman and the Wolf Fall into the Pit Together", emoji: "🦁" },
  { id: "atu-183-the-hare-promises-to-dance", atu: "183*", title: "The Hare Promises to Dance", emoji: "🦁" },
  { id: "atu-184-half-of-the-money-thrown-into", atu: "184", title: "Half of the Money Thrown into Water", emoji: "🐭" },
  { id: "atu-185-the-nightcap-dealer-and-the-monkeys", atu: "185", title: "The Nightcap Dealer and the Monkeys", emoji: "🦁" },
  { id: "atu-186-the-monkey-and-the-nut", atu: "186", title: "The Monkey and the Nut", emoji: "🐢" },
  { id: "atu-200a-the-dog-loses-a-certificate", atu: "200A", title: "The Dog Loses a Certificate", emoji: "🐢" },
  { id: "atu-202-the-two-stubborn-goats", atu: "202", title: "The Two Stubborn Goats", emoji: "🐦" },
  { id: "atu-204-animals-in-peril-at-sea", atu: "204", title: "Animals in Peril at Sea", emoji: "🦁" },
  { id: "atu-214-the-donkey-tries-to-caress-his", atu: "214", title: "The Donkey Tries to Caress His Master", emoji: "🐭" },
  { id: "atu-214b-the-donkey-in-lion-s-skin", atu: "214B", title: "The Donkey in Lion’s Skin", emoji: "🐭" },
  { id: "atu-215-a-jackdaw-tries-to-carry-off", atu: "215", title: "A Jackdaw (Crow) Tries to Carry Off a Lamb as an Eagle Does", emoji: "🦁" },
  { id: "atu-217-the-cat-with-the-candle", atu: "217", title: "The Cat with the Candle", emoji: "🦊" },
  { id: "atu-218-a-cat-transformed-to-a-maiden", atu: "218", title: "A Cat Transformed to a Maiden Runs after a Mouse", emoji: "🐻" },
  { id: "atu-219f-the-dog-and-the-sow-argue", atu: "219F*", title: "The Dog and the Sow Argue", emoji: "🦁" },
  { id: "atu-219h-the-rooster-and-the-pearl", atu: "219H*", title: "The Rooster and the Pearl", emoji: "🐦" },
  { id: "atu-220-the-council-of-birds", atu: "220", title: "The Council of Birds", emoji: "🦊" },
  { id: "atu-224-bird-wedding", atu: "224", title: "Bird (Beetle) Wedding", emoji: "🐦" },
  { id: "atu-230-the-race-of-the-rooster-the", atu: "230*", title: "The Race of the Rooster, the Birch-Cock and the Birch-Hen", emoji: "🐰" },
  { id: "atu-232-the-birch-cock-and-the-birds", atu: "232", title: "The Birch-Cock and the Birds of Passage", emoji: "🐻" },
  { id: "atu-232d-a-crow-drops-pebbles-into-a", atu: "232D*", title: "A Crow Drops Pebbles into a Water Jug", emoji: "🐢" },
  { id: "atu-233b-the-birds-fly-off-with-the", atu: "233B", title: "The Birds Fly Off with the Net", emoji: "🦊" },
  { id: "atu-233d-the-birds-and-the-fowler", atu: "233D", title: "The Birds and the Fowler", emoji: "🐺" },
  { id: "atu-235-the-jay-borrows-the-cuckoo-s", atu: "235", title: "The Jay Borrows the Cuckoo’s Skin", emoji: "🐦" },
  { id: "atu-235c-a-bird-has-new-clothes-made", atu: "235C*", title: "A Bird Has New Clothes Made", emoji: "🐰" },
  { id: "atu-236-the-magpie-teaches-the-dove-to", atu: "236", title: "The Magpie Teaches the Dove to Build a Nest", emoji: "🐭" },
  { id: "atu-236-miscellaneous-tales-with-imitation-of-bird", atu: "236*", title: "Miscellaneous Tales with Imitation of Bird Sounds", emoji: "🐭" },
  { id: "atu-238-the-dove-and-the-frog-boast", atu: "238", title: "The Dove and the Frog Boast to Each Other", emoji: "🐢" },
  { id: "atu-239-the-crow-helps-the-deer-escape", atu: "239", title: "The Crow Helps the Deer Escape from the Snare", emoji: "🦊" },
  { id: "atu-240-the-dove-trades-her-eggs", atu: "240", title: "The Dove Trades Her Eggs", emoji: "🦁" },
  { id: "atu-244-the-raven-in-borrowed-feathers", atu: "244", title: "The Raven in Borrowed Feathers", emoji: "🐺" },
  { id: "atu-253-the-fish-in-the-net", atu: "253", title: "The Fish in the Net", emoji: "🦊" },
  { id: "atu-275a-the-race-between-hare-and-tortoise", atu: "275A", title: "The Race between Hare and Tortoise", emoji: "🐻" },
  { id: "atu-276-the-crab-walks-backward-learned-from", atu: "276", title: "The Crab Walks Backward: Learned from His Parents", emoji: "🐻" },
  { id: "atu-277a-the-frog-tries-in-vain-to", atu: "277A", title: "The Frog Tries in Vain to be as Big as the Ox", emoji: "🐢" },
  { id: "atu-278-the-frog-and-the-mouse-tied", atu: "278", title: "The Frog and the Mouse Tied Together", emoji: "🐰" },
  { id: "atu-278a-frogs-decide-not-to-jump-into", atu: "278A*", title: "Frogs Decide Not to Jump into the Well", emoji: "🐦" },
  { id: "atu-280-the-ant-carries-a-load-as", atu: "280", title: "The Ant Carries a Load as Large as Himself", emoji: "🐺" },
  { id: "atu-282b-conversation-of-fly-and-flea", atu: "282B*", title: "Conversation of Fly and Flea", emoji: "🐦" },
  { id: "atu-285b-falling-nut-saves-man-from-snake", atu: "285B", title: "Falling Nut Saves Man from Snake", emoji: "🐰" },
  { id: "atu-285e-the-snake-tries-to-bite-on", atu: "285E", title: "The Snake Tries to Bite on a File", emoji: "🦁" },
  { id: "atu-288b-festina-lente", atu: "288B**", title: "Festina Lente (Haste Makes Waste)", emoji: "🦊" },
  { id: "atu-289-a-bat-a-diver-and-a", atu: "289", title: "A Bat, a Diver, and a Thornbush Shipwrecked", emoji: "🐰" },
  { id: "atu-293-the-debate-of-the-belly-and", atu: "293", title: "The Debate of the Belly and the Members", emoji: "🐦" },
  { id: "atu-296-the-clay-pot-and-the-brass", atu: "296", title: "The Clay Pot and the Brass Pot in the River", emoji: "🐢" },
  { id: "atu-298c-the-reeds-bend-before-wind", atu: "298C*", title: "The Reeds Bend before Wind (Flood)", emoji: "🦊" },
  { id: "atu-299-the-mountain-gives-birth-to-a", atu: "299", title: "The Mountain Gives Birth to a Mouse", emoji: "🐺" },
  { id: "atu-302c-the-magic-horse", atu: "302C*", title: "The Magic Horse", emoji: "🌙" },
  { id: "atu-314a-the-shepherd-and-the-three-giants", atu: "314A", title: "The Shepherd and the Three Giants", emoji: "🧚" },
  { id: "atu-321-eyes-recovered-from-witch", atu: "321", title: "Eyes Recovered from Witch", emoji: "🏰" },
  { id: "atu-325-the-magician-and-his-pupil", atu: "325", title: "The Magician and His Pupil", emoji: "🗝️" },
  { id: "atu-369-the-youth-on-a-quest-for", atu: "369", title: "The Youth on a Quest for His Lost Father", emoji: "🗝️" },
  { id: "atu-401a-the-soldiers-in-the-enchanted-castle", atu: "401A*", title: "The Soldiers in the Enchanted Castle", emoji: "🗝️" },
  { id: "atu-408-the-three-oranges", atu: "408", title: "The Three Oranges", emoji: "🌙" },
  { id: "atu-412-the-maiden-with-a-separable-soul", atu: "412", title: "The Maiden (Youth) with a Separable Soul in a Necklace", emoji: "🔮" },
  { id: "atu-425-the-insulted-bridegroom-disenchanted", atu: "425*", title: "The Insulted Bridegroom Disenchanted", emoji: "🧚" },
  { id: "atu-425d-the-vanished-husband", atu: "425D", title: "The Vanished Husband", emoji: "🔮" },
  { id: "atu-425e-the-enchanted-husband-sings-lullaby", atu: "425E", title: "The Enchanted Husband Sings Lullaby", emoji: "🗝️" },
  { id: "atu-426-the-two-girls-the-bear-and", atu: "426", title: "The Two Girls, the Bear, and the Dwarf", emoji: "✨" },
  { id: "atu-430-the-donkey", atu: "430", title: "The Donkey", emoji: "🪄" },
  { id: "atu-434-the-diver", atu: "434*", title: "The Diver", emoji: "🔮" },
  { id: "atu-442-the-old-woman-in-the-forest", atu: "442", title: "The Old Woman in the Forest", emoji: "🏰" },
  { id: "atu-460a-the-journey-to-god", atu: "460A", title: "The Journey to God (Fortune)", emoji: "🧚" },
  { id: "atu-465-go-i-know-not-whither-and", atu: "465", title: "Go I Know Not Whither and Fetch I Know Not What", emoji: "🧚" },
  { id: "atu-471a-the-monk-and-the-bird", atu: "471A", title: "The Monk and the Bird", emoji: "🧚" },
  { id: "atu-476-coal-turns-into-gold", atu: "476", title: "Coal Turns into Gold", emoji: "🧚" },
  { id: "atu-476-midwife-in-the-underworld", atu: "476**", title: "Midwife in the Underworld", emoji: "🧚" },
  { id: "atu-513b-the-land-and-water-ship", atu: "513B", title: "The Land and Water Ship", emoji: "🧚" },
  { id: "atu-514-the-shift-of-sex", atu: "514", title: "The Shift of Sex", emoji: "✨" },
  { id: "atu-514-a-young-woman-disguised-as-a", atu: "514**", title: "A Young Woman Disguised as a Man is Wooed by the Queen", emoji: "✨" },
  { id: "atu-515-the-shepherd-boy", atu: "515", title: "The Shepherd Boy", emoji: "🪄" },
  { id: "atu-517-the-boy-who-understands-the-language", atu: "517", title: "The Boy Who Understands the Language of Birds", emoji: "🧚" },
  { id: "atu-552-the-girls-who-married-animals", atu: "552", title: "The Girls Who Married Animals", emoji: "🏰" },
  { id: "atu-554-the-grateful-animals", atu: "554", title: "The Grateful Animals", emoji: "🌙" },
  { id: "atu-556f-the-shepherd-in-the-service-of", atu: "556F*", title: "The Shepherd in the Service of a Witch", emoji: "🏰" },
  { id: "atu-570-the-rat-catcher", atu: "570*", title: "The Rat-Catcher", emoji: "🌙" },
  { id: "atu-570a-the-princess-and-the-magic-shell", atu: "570A", title: "The Princess and the Magic Shell", emoji: "🧚" },
  { id: "atu-593-fiddevav", atu: "593", title: "Fiddevav", emoji: "🌟" },
  { id: "atu-660-the-three-doctors", atu: "660", title: "The Three Doctors", emoji: "✨" },
  { id: "atu-678-the-king-transfers-his-soul-to", atu: "678", title: "The King Transfers His Soul to a Parrot", emoji: "🌟" },
  { id: "atu-681-relativity-of-time", atu: "681", title: "Relativity of Time", emoji: "🌟" },
  { id: "atu-682-meditation-on-the-trinity", atu: "682", title: "Meditation on the Trinity", emoji: "✨" },
  { id: "atu-706d-st-wilgefortis-and-her-beard", atu: "706D", title: "St. Wilgefortis and Her Beard", emoji: "🌟" },
  { id: "atu-708-the-wonder-child", atu: "708", title: "The Wonder Child", emoji: "🌟" },
  { id: "atu-715a-the-wonderful-rooster", atu: "715A", title: "The Wonderful Rooster", emoji: "🗝️" },
  { id: "atu-735-the-rich-man-s-and-the", atu: "735", title: "The Rich Man’s and the Poor Man’s Fortune", emoji: "🪄" },
  { id: "atu-736-luck-and-wealth", atu: "736", title: "Luck and Wealth", emoji: "🏰" },
  { id: "atu-736a-the-ring-of-polycrates", atu: "736A", title: "The Ring of Polycrates", emoji: "🌟" },
  { id: "atu-737b-the-lucky-wife", atu: "737B*", title: "The Lucky Wife", emoji: "🧚" },
  { id: "atu-739-the-luck-bringing-animal", atu: "739*", title: "The Luck-Bringing Animal", emoji: "🔮" },
  { id: "atu-745-hatch-penny", atu: "745", title: "Hatch-Penny", emoji: "✨" },
  { id: "atu-745a-the-predestined-treasure", atu: "745A", title: "The Predestined Treasure", emoji: "🪄" },
  { id: "atu-752b-the-forgotten-wind", atu: "752B", title: "The Forgotten Wind", emoji: "🕯️" },
  { id: "atu-754-lucky-poverty", atu: "754", title: "Lucky Poverty", emoji: "🕊️" },
  { id: "atu-754-st-peter-and-his-wife", atu: "754**", title: "St. Peter and His Wife", emoji: "🕯️" },
  { id: "atu-756e-charity-rewarded", atu: "756E*", title: "Charity Rewarded", emoji: "🙏" },
  { id: "atu-759e-the-miller-of-sans-souci", atu: "759E", title: "The Miller of Sans Souci", emoji: "🕯️" },
  { id: "atu-760-salvation-in-the-cradle", atu: "760***", title: "Salvation in the Cradle", emoji: "🙏" },
  { id: "atu-766-the-seven-sleepers", atu: "766", title: "The Seven Sleepers", emoji: "🙏" },
  { id: "atu-767-food-for-the-crucifix", atu: "767", title: "Food for the Crucifix", emoji: "🕯️" },
  { id: "atu-768-st-christopher-and-the-christ-child", atu: "768", title: "St. Christopher and the Christ Child", emoji: "🕊️" },
  { id: "atu-770a-guardian-angel", atu: "770A*", title: "Guardian Angel", emoji: "🕊️" },
  { id: "atu-772-the-flies-instead-of-nails-on", atu: "772*", title: "The Flies Instead of Nails on Christ's Heart", emoji: "🌾" },
  { id: "atu-774-christ-and-st-peter", atu: "774", title: "Christ and St. Peter", emoji: "🌾" },
  { id: "atu-774d-st-peter-acts-as-god-for", atu: "774D", title: "St. Peter Acts as God for a Day", emoji: "🕊️" },
  { id: "atu-774l-mushrooms-from-st-peter-s-spittle", atu: "774L", title: "Mushrooms from St. Peter’s Spittle", emoji: "🙏" },
  { id: "atu-774p-st-peter-and-the-nuts", atu: "774P", title: "St. Peter and the Nuts", emoji: "🌾" },
  { id: "atu-775-midas-short-sighted-wish", atu: "775", title: "Midas’ Short-sighted Wish", emoji: "🙏" },
  { id: "atu-779h-star-money", atu: "779H*", title: "Star Money", emoji: "⛪" },
  { id: "atu-798-woman-created-from-a-monkey-s", atu: "798", title: "Woman Created from a Monkey’s Tail", emoji: "🙏" },
  { id: "atu-802-the-farmer-in-heaven", atu: "802", title: "The Farmer in Heaven", emoji: "🕯️" },
  { id: "atu-804-st-peter-s-mother-falls-from", atu: "804", title: "St. Peter’s Mother Falls from Heaven", emoji: "⛪" },
  { id: "atu-805-joseph-and-mary-threaten-to-leave", atu: "805", title: "Joseph and Mary Threaten to Leave Heaven", emoji: "🌾" },
  { id: "atu-813-not-to-sleep-three-nights", atu: "813*", title: "Not to Sleep Three Nights", emoji: "🙏" },
  { id: "atu-821b-chickens-from-boiled-eggs", atu: "821B", title: "Chickens from Boiled Eggs", emoji: "⛪" },
  { id: "atu-827-a-pious-innocent-man-knows-nothing", atu: "827", title: "A Pious Innocent Man Knows Nothing of God", emoji: "⛪" },
  { id: "atu-830b-my-crops-will-thrive-here-without", atu: "830B", title: "“My Crops Will Thrive Here without God’s Blessing”", emoji: "⛪" },
  { id: "atu-830c-if-god-wills", atu: "830C", title: "“If God Wills”", emoji: "🌾" },
  { id: "atu-842c-floating-coins", atu: "842C*", title: "Floating Coins", emoji: "🌾" },
  { id: "atu-843-the-lazy-weaving-woman", atu: "843*", title: "The Lazy Weaving Woman", emoji: "⛪" },
  { id: "atu-844-the-luck-bringing-shirt", atu: "844", title: "The Luck-Bringing Shirt", emoji: "🕊️" },
  { id: "atu-853-the-hero-catches-the-princess-with", atu: "853", title: "The Hero Catches the Princess with Her Own Words", emoji: "🧭" },
  { id: "atu-853a-no", atu: "853A", title: "“No”", emoji: "🧭" },
  { id: "atu-854-the-golden-ram", atu: "854", title: "The Golden Ram", emoji: "🎒" },
  { id: "atu-857-the-louse-skin", atu: "857", title: "The Louse-Skin", emoji: "🧵" },
  { id: "atu-859-the-penniless-bridegroom-pretends-to-wealth", atu: "859", title: "The Penniless Bridegroom Pretends to Wealth", emoji: "🎒" },
  { id: "atu-862-he-that-asketh-shall-receive", atu: "862", title: "“He that Asketh Shall Receive”", emoji: "🧭" },
  { id: "atu-871-the-princess-who-goes-to-seek", atu: "871*", title: "The Princess Who Goes to Seek Trouble", emoji: "🏡" },
  { id: "atu-874-ariadne-s-thread", atu: "874*", title: "Ariadne’s Thread", emoji: "🧭" },
  { id: "atu-875-the-women-of-weinsberg", atu: "875*", title: "The Women of Weinsberg", emoji: "🎒" },
  { id: "atu-875b-the-clever-girl-and-the-king", atu: "875B", title: "The Clever Girl and the King", emoji: "🧭" },
  { id: "atu-875e-the-unjust-decision-the-oil-press", atu: "875E", title: "The Unjust Decision: The Oil Press Gives Birth to a Foal", emoji: "🛤️" },
  { id: "atu-877-the-old-woman-who-was-skinned", atu: "877", title: "The Old Woman Who Was Skinned", emoji: "🎒" },
  { id: "atu-879-the-basil-maiden", atu: "879", title: "The Basil Maiden", emoji: "🛤️" },
  { id: "atu-879a-fisher-husband-of-the-princess", atu: "879A", title: "Fisher Husband of the Princess", emoji: "🛤️" },
  { id: "atu-880-a-man-boasts-of-his-wife", atu: "880", title: "A Man Boasts of His Wife", emoji: "🧭" },
  { id: "atu-886-the-girl-who-could-not-keep", atu: "886", title: "The Girl Who Could Not Keep the Secret", emoji: "🎒" },
  { id: "atu-887a-precious-stones-in-bricks", atu: "887A*", title: "Precious Stones in Bricks", emoji: "🧵" },
  { id: "atu-890-the-debtor-s-bed", atu: "890**", title: "The Debtor’s Bed", emoji: "🧭" },
  { id: "atu-901-taming-of-the-shrew", atu: "901", title: "Taming of the Shrew", emoji: "🧵" },
  { id: "atu-903c-mother-in-law-and-daughter-in", atu: "903C*", title: "Mother-in-Law and Daughter-in-Law", emoji: "🧭" },
  { id: "atu-910-the-clever-precepts", atu: "910", title: "The Clever Precepts", emoji: "🧵" },
  { id: "atu-910e-find-the-treasure-in-our-vineyard", atu: "910E", title: "“Find the Treasure in Our Vineyard!”", emoji: "🛤️" },
  { id: "atu-910f-the-quarreling-sons-and-the-bundle", atu: "910F", title: "The Quarreling Sons and the Bundle of Twigs", emoji: "🧵" },
  { id: "atu-910g-man-buys-a-pennyworth-of-wit", atu: "910G", title: "Man Buys a Pennyworth of Wit", emoji: "🧭" },
  { id: "atu-915-all-depends-on-how-you-take", atu: "915", title: "All Depends on How You Take It", emoji: "🧵" },
  { id: "atu-915a-the-misunderstood-precepts", atu: "915A", title: "The Misunderstood Precepts", emoji: "🧵" },
  { id: "atu-920a-the-case-of-the-boiled-eggs", atu: "920A", title: "The Case of the Boiled Eggs", emoji: "🧭" },
  { id: "atu-920b-the-birds-chosen-by-the-sons", atu: "920B", title: "The Birds Chosen by the Sons", emoji: "🎒" },
  { id: "atu-920d-the-four-princes", atu: "920D", title: "The Four Princes", emoji: "🛤️" },
  { id: "atu-920e-the-three-rings", atu: "920E", title: "The Three Rings", emoji: "🧵" },
  { id: "atu-921a-the-sharing-of-bread-or-money", atu: "921A", title: "The Sharing of Bread Or Money", emoji: "🎒" },
  { id: "atu-921b-best-friend-worst-enemy", atu: "921B", title: "Best Friend, Worst Enemy", emoji: "🏡" },
  { id: "atu-921c-why-hair-of-head-is-gray", atu: "921C", title: "Why Hair of Head is Gray before the Beard", emoji: "🛤️" },
  { id: "atu-921c-astronomer-and-doctor-at-farmer-s", atu: "921C*", title: "Astronomer and Doctor at Farmer’s House", emoji: "🧭" },
  { id: "atu-921e-never-heard-before", atu: "921E", title: "Never Heard Before", emoji: "🧭" },
  { id: "atu-921f-philosopher-spits-in-the-king-s", atu: "921F", title: "Philosopher Spits in the King’s Beard", emoji: "🎒" },
  { id: "atu-922b-the-king-s-face-on-the", atu: "922B", title: "The King’s Face on the Coin", emoji: "🛤️" },
  { id: "atu-923a-like-wind-in-the-hot-sun", atu: "923A", title: "Like Wind in the Hot Sun", emoji: "🛤️" },
  { id: "atu-924-discussion-in-sign-language", atu: "924", title: "Discussion in Sign Language", emoji: "🧵" },
  { id: "atu-925-tidings-for-the-king", atu: "925", title: "Tidings for the King", emoji: "🧭" },
  { id: "atu-925-the-most-beautiful-in-the-garden", atu: "925*", title: "The Most Beautiful in the Garden", emoji: "🏡" },
  { id: "atu-926-judgment-of-solomon", atu: "926", title: "Judgment of Solomon", emoji: "🎒" },
  { id: "atu-926c-the-betrothed-children", atu: "926C*", title: "The Betrothed Children", emoji: "🧭" },
  { id: "atu-927a-old-saddle-granted-by-the-king", atu: "927A*", title: "“Old Saddle” Granted by the King", emoji: "🧵" },
  { id: "atu-927c-the-ground-is-measured-with-a", atu: "927C*", title: "The Ground is Measured with a Horse's Skin (Ox Hide)", emoji: "🎒" },
  { id: "atu-928-planting-for-the-next-generation", atu: "928", title: "Planting for the Next Generation", emoji: "🛤️" },
  { id: "atu-929a-uneducated-father", atu: "929A", title: "Uneducated Father", emoji: "🧵" },
  { id: "atu-934f-the-man-in-the-well", atu: "934F", title: "The Man in the Well", emoji: "🧭" },
  { id: "atu-935-the-prodigal-s-return", atu: "935", title: "The Prodigal’s Return", emoji: "🎒" },
  { id: "atu-935-the-stepson-mariner", atu: "935*", title: "The Stepson Mariner", emoji: "🛤️" },
  { id: "atu-936-the-golden-mountain", atu: "936*", title: "The Golden Mountain", emoji: "🧵" },
  { id: "atu-938-placidas", atu: "938", title: "Placidas", emoji: "🧵" },
  { id: "atu-938a-misfortunes-in-youth", atu: "938A", title: "Misfortunes in Youth", emoji: "🧵" },
  { id: "atu-938b-better-in-youth", atu: "938B", title: "Better in Youth", emoji: "🧭" },
  { id: "atu-939-the-offended-deity", atu: "939", title: "The Offended Deity", emoji: "🧭" },
  { id: "atu-940-the-forgiven-debt", atu: "940*", title: "The Forgiven Debt", emoji: "🧵" },
  { id: "atu-944-king-for-a-year", atu: "944", title: "King for a Year", emoji: "🎒" },
  { id: "atu-944-easy-come-easy-go", atu: "944*", title: "“Easy Come, Easy Go!”", emoji: "🛤️" },
  { id: "atu-945-luck-and-intelligence", atu: "945", title: "Luck and Intelligence", emoji: "🏡" },
  { id: "atu-945a-money-and-fortune", atu: "945A*", title: "Money and Fortune", emoji: "🧵" },
  { id: "atu-947-the-man-followed-by-bad-luck", atu: "947", title: "The Man Followed by Bad Luck", emoji: "🧵" },
  { id: "atu-958f-test-of-sex-catching-an-apple", atu: "958F*", title: "Test of Sex: Catching an Apple", emoji: "🛤️" },
  { id: "atu-960c-the-miracle-of-the-cooked-chicken", atu: "960C", title: "The Miracle of the Cooked Chicken", emoji: "🎒" },
  { id: "atu-967-the-man-saved-by-a-spider", atu: "967", title: "The Man Saved by a Spider Web", emoji: "🎒" },
  { id: "atu-983-the-dishes-of-the-same-flavor", atu: "983", title: "The Dishes of the Same Flavor", emoji: "🧵" },
  { id: "atu-987-false-magician-exposed-by-clever-girl", atu: "987", title: "False Magician Exposed by Clever Girl", emoji: "🛤️" },
  { id: "atu-2009-origin-of-chess", atu: "2009", title: "Origin of Chess", emoji: "🎶" },
  { id: "atu-2010-ehod-mi-yodea", atu: "2010", title: "Ehod mi yodea (One; Who Knows)", emoji: "🔁" },
  { id: "atu-2010a-the-twelve-days-of-christmas", atu: "2010A", title: "The Twelve Days (Gifts) of Christmas", emoji: "🔁" },
  { id: "atu-2010i-how-the-rich-man-paid-his", atu: "2010I", title: "How the Rich Man Paid his Servant", emoji: "🎶" },
  { id: "atu-2010ia-the-animals-with-peculiar-names", atu: "2010IA", title: "The Animals with Peculiar Names (previously The Animals with Queer Names)", emoji: "🎶" },
  { id: "atu-2013-there-was-once-a-woman-the", atu: "2013", title: "'There Was Once a Woman; the Woman Had a Son", emoji: "🎶" },
  { id: "atu-2016-wee-wee-woman", atu: "2016", title: "Wee Wee Woman (previously There Was a Wee Wee Woman)", emoji: "🪜" },
  { id: "atu-2019-pif-paf-poltrie", atu: "2019", title: "Pif Paf Poltrie", emoji: "♾️" },
  { id: "atu-2019-louse-and-flea-wish-to-marry", atu: "2019*", title: "Louse and Flea Wish to Marry", emoji: "🪜" },
  { id: "atu-2031a-the-esdras-chain-stronger-and-strongest", atu: "2031A", title: "The Esdras Chain: Stronger and Strongest", emoji: "🎶" },
  { id: "atu-2031b-abraham-learns-to-worship-god", atu: "2031B", title: "Abraham Learns to Worship God", emoji: "♾️" },
  { id: "atu-2031c-the-mightiest-being-as-husband-for", atu: "2031C", title: "The Mightiest Being as Husband for the Daughter (previously The Man Seeks the Greatest Being as a Husband for his Daughter)", emoji: "🔁" },
  { id: "atu-2034-the-mouse-regains-its-tail", atu: "2034", title: "The Mouse Regains its Tail", emoji: "🪜" },
  { id: "atu-2039-the-horseshoe-nail", atu: "2039", title: "The Horseshoe Nail", emoji: "🪜" },
  { id: "atu-2250-unfinished-tales", atu: "2250", title: "Unfinished Tales", emoji: "🪜" },
  { id: "atu-2301-corn-carried-away-one-grain-at", atu: "2301", title: "Corn Carried Away One Grain at a Time", emoji: "🎶" },
  { id: "atu-2302-the-crow-on-the-tarred-bridge", atu: "2302", title: "The Crow on the Tarred Bridge", emoji: "♾️" },
  { id: "atu-2335-tales-filled-with-contradictions", atu: "2335", title: "Tales Filled with Contradictions", emoji: "🔁" },
];
