/**
 * GENERATED FILE — do not edit by hand.
 *
 * Written by `npm run tale-catalogue:build` from `lib/tale-types.ts`,
 * `lib/tale-types-curated.ts` and `lib/tale-types-extended-authored.ts`.
 * Carries the six fields a picker card or the story form needs — never the
 * beats, signature elements, tone, or example opener that steer the prompt.
 * Those stay in the full `TaleType` registry,
 * imported only by `lib/prompt.ts` and `lib/mock.ts` (both server-only), so
 * that prose never rides along into a "use client" bundle.
 */

export interface TaleTypeSummary {
  id: string;
  label: string;
  atuNumber: string;
  category: string;
  emoji: string;
  tagline: string;
}

/** The twelve original tale types, picker-card fields only. */
export const ORIGINAL_TALE_TYPE_SUMMARIES: readonly TaleTypeSummary[] = [
  {
    id: "cinderella",
    label: "Cinderella",
    atuNumber: "ATU 510A",
    category: "Tales of Magic",
    emoji: "🩰",
    tagline: "A kind heart, a magical helper, a token found.",
  },
  {
    id: "kind-and-unkind-girls",
    label: "The Kind and the Unkind Girls",
    atuNumber: "ATU 480",
    category: "Tales of Magic",
    emoji: "🌸",
    tagline: "Small kindnesses along a road, quietly repaid.",
  },
  {
    id: "beauty-and-the-beast",
    label: "Beauty and the Beast",
    atuNumber: "ATU 425C",
    category: "Tales of Magic",
    emoji: "🌹",
    tagline: "Kindness that sees past a strange outside.",
  },
  {
    id: "sleeping-beauty",
    label: "Sleeping Beauty",
    atuNumber: "ATU 410",
    category: "Tales of Magic",
    emoji: "😴",
    tagline: "A whole kingdom drifting gently off to sleep.",
  },
  {
    id: "the-frog-king",
    label: "The Frog King",
    atuNumber: "ATU 440",
    category: "Tales of Magic",
    emoji: "🐸",
    tagline: "A promise kept, and a friend set free.",
  },
  {
    id: "the-dragon-slayer",
    label: "The Dragon-Slayer",
    atuNumber: "ATU 300",
    category: "Tales of Magic",
    emoji: "🐉",
    tagline: "A brave hero, loyal animals, a worried dragon soothed.",
  },
  {
    id: "puss-in-boots",
    label: "Puss in Boots",
    atuNumber: "ATU 545B",
    category: "Tales of Magic",
    emoji: "🐈",
    tagline: "A clever cat who winks fortune into being.",
  },
  {
    id: "thumbling",
    label: "Thumbling (Tom Thumb)",
    atuNumber: "ATU 700",
    category: "Tales of Magic",
    emoji: "👣",
    tagline: "A thumb-sized hero and a great big, gentle world.",
  },
  {
    id: "wolf-and-the-kids",
    label: "The Wolf and the Kids",
    atuNumber: "ATU 123",
    category: "Animal Tales",
    emoji: "🐐",
    tagline: "Clever little ones who see through a sly trick.",
  },
  {
    id: "bremen-town-musicians",
    label: "The Bremen Town Musicians",
    atuNumber: "ATU 130",
    category: "Animal Tales",
    emoji: "🎻",
    tagline: "Four old friends who find a home in a song.",
  },
  {
    id: "the-gingerbread-man",
    label: "The Gingerbread Man",
    atuNumber: "ATU 2025",
    category: "Formula Tales",
    emoji: "🍪",
    tagline: "A runaway treat and a merry, growing chase.",
  },
  {
    id: "chicken-little",
    label: "Chicken Little",
    atuNumber: "ATU 2033",
    category: "Formula Tales",
    emoji: "🐤",
    tagline: "A tiny worry that grows, then gently melts away.",
  },
];

/** The fifty formerly catalogue-only tale types, picker-card fields only. */
export const CURATED_TALE_TYPE_SUMMARIES: readonly TaleTypeSummary[] = [
  {
    id: "how-the-bear-lost-his-tail",
    label: "How the Bear Lost His Tail",
    atuNumber: "ATU 2",
    category: "Animal Tales",
    emoji: "🐻",
    tagline: "A long tail, a frozen lake, and a lesson learned the chilly way.",
  },
  {
    id: "the-fox-and-the-crow",
    label: "The Fox and the Crow",
    atuNumber: "ATU 57",
    category: "Animal Tales",
    emoji: "🧀",
    tagline: "A song asked for, a cheese let go, and a compliment seen through.",
  },
  {
    id: "the-fox-and-the-grapes",
    label: "The Fox and the Grapes",
    atuNumber: "ATU 59",
    category: "Animal Tales",
    emoji: "🍇",
    tagline: "High grapes, tired legs, and the comfort of letting go.",
  },
  {
    id: "the-fox-and-the-crane",
    label: "The Fox and the Crane",
    atuNumber: "ATU 60",
    category: "Animal Tales",
    emoji: "🍽️",
    tagline: "Two dinners, two wrong dishes, and a friendship that survives them.",
  },
  {
    id: "more-timid-than-the-hare",
    label: "More Timid Than the Hare",
    atuNumber: "ATU 70",
    category: "Animal Tales",
    emoji: "🐇",
    tagline: "Hares who think they are the most frightened creatures alive, until they meet the frogs.",
  },
  {
    id: "the-wolf-and-the-crane",
    label: "The Wolf and the Crane",
    atuNumber: "ATU 76",
    category: "Animal Tales",
    emoji: "🕊️",
    tagline: "A bone in a throat, a long beak, and a wage never paid.",
  },
  {
    id: "the-vain-little-stag",
    label: "The Vain Little Stag",
    atuNumber: "ATU 77",
    category: "Animal Tales",
    emoji: "🦌",
    tagline: "Beautiful antlers, unremarkable legs, and which of them turns out to matter.",
  },
  {
    id: "the-mouse-the-bird-and-the-sausage",
    label: "The Mouse, the Bird, and the Sausage",
    atuNumber: "ATU 85",
    category: "Animal Tales",
    emoji: "🐭",
    tagline: "Three housemates, three jobs, and what happens when they swap.",
  },
  {
    id: "the-cat-and-the-fox",
    label: "The Cat and the Fox",
    atuNumber: "ATU 105",
    category: "Animal Tales",
    emoji: "🐱",
    tagline: "A hundred ways to escape, one way that works.",
  },
  {
    id: "belling-the-cat",
    label: "Belling the Cat",
    atuNumber: "ATU 110",
    category: "Animal Tales",
    emoji: "🔔",
    tagline: "A brilliant plan, and the small matter of who will carry it out.",
  },
  {
    id: "town-mouse-and-country-mouse",
    label: "Town Mouse and Country Mouse",
    atuNumber: "ATU 112",
    category: "Animal Tales",
    emoji: "🏙️",
    tagline: "A rich table with interruptions, and a plain one with peace.",
  },
  {
    id: "the-three-little-pigs",
    label: "The Three Little Pigs",
    atuNumber: "ATU 124",
    category: "Animal Tales",
    emoji: "🐷",
    tagline: "Straw, sticks, bricks, and a huffing visitor who is mostly out of breath.",
  },
  {
    id: "how-dogs-and-cats-became-rivals",
    label: "How Dogs and Cats Became Rivals",
    atuNumber: "ATU 200",
    category: "Animal Tales",
    emoji: "🐕",
    tagline: "A lost paper, a misplaced trust, and why one of them still watches the other.",
  },
  {
    id: "the-election-of-the-bird-king",
    label: "The Election of the Bird-King",
    atuNumber: "ATU 221",
    category: "Animal Tales",
    emoji: "🐦",
    tagline: "Whoever flies highest shall be king — and a very small bird has been thinking.",
  },
  {
    id: "the-geese-and-the-last-prayer",
    label: "The Geese and the Last Prayer",
    atuNumber: "ATU 227",
    category: "Animal Tales",
    emoji: "🪿",
    tagline: "A flock with one more thing to say, and a story with no end in sight.",
  },
  {
    id: "the-fox-and-the-crayfish",
    label: "The Fox and the Crayfish",
    atuNumber: "ATU 275",
    category: "Animal Tales",
    emoji: "🦀",
    tagline: "A race against someone who has thought about it more carefully.",
  },
  {
    id: "the-wind-and-the-sun",
    label: "The Wind and the Sun",
    atuNumber: "ATU 298",
    category: "Animal Tales",
    emoji: "☀️",
    tagline: "Two forces argue about strength, and a traveller's coat decides it.",
  },
  {
    id: "the-twelve-dancing-princesses",
    label: "The Twelve Dancing Princesses",
    atuNumber: "ATU 306",
    category: "Tales of Magic",
    emoji: "👠",
    tagline: "Twelve pairs of worn-through shoes, and a secret staircase under the floor.",
  },
  {
    id: "rapunzel",
    label: "Rapunzel",
    atuNumber: "ATU 310",
    category: "Tales of Magic",
    emoji: "🌷",
    tagline: "A tower, a long golden braid, and a window that finally opens.",
  },
  {
    id: "the-magic-flight",
    label: "The Magic Flight",
    atuNumber: "ATU 313",
    category: "Tales of Magic",
    emoji: "🪄",
    tagline: "A comb, a mirror, a hairbrush — and each one becomes a whole landscape.",
  },
  {
    id: "jack-and-the-beanstalk",
    label: "Jack and the Beanstalk",
    atuNumber: "ATU 328",
    category: "Tales of Magic",
    emoji: "🌱",
    tagline: "Five odd beans, a vine into the clouds, and a household in the sky.",
  },
  {
    id: "the-animal-bride",
    label: "The Animal Bride",
    atuNumber: "ATU 402",
    category: "Tales of Magic",
    emoji: "🐭",
    tagline: "A companion who is not what they seem, and a friend who waits to find out.",
  },
  {
    id: "east-of-the-sun-west-of-the-moon",
    label: "East of the Sun and West of the Moon",
    atuNumber: "ATU 425A",
    category: "Tales of Magic",
    emoji: "🌗",
    tagline: "A journey past the edge of every map, with the winds for company.",
  },
  {
    id: "rumpelstiltskin",
    label: "Rumpelstiltskin",
    atuNumber: "ATU 500",
    category: "Tales of Magic",
    emoji: "🧵",
    tagline: "Straw spun to gold, an impossible bargain, and a name overheard in a wood.",
  },
  {
    id: "the-three-spinners",
    label: "The Three Spinners",
    atuNumber: "ATU 501",
    category: "Tales of Magic",
    emoji: "🧶",
    tagline: "Three strange helpers at the door, and a debt paid in kindness.",
  },
  {
    id: "one-eye-two-eyes-three-eyes",
    label: "One-Eye, Two-Eyes, and Three-Eyes",
    atuNumber: "ATU 511",
    category: "Tales of Magic",
    emoji: "🌳",
    tagline: "A sister who is different, a goat who helps, and a tree only she can pick from.",
  },
  {
    id: "the-extraordinary-companions",
    label: "The Extraordinary Companions",
    atuNumber: "ATU 513",
    category: "Tales of Magic",
    emoji: "💪",
    tagline: "Six friends with six impossible talents, and a task that needs all of them.",
  },
  {
    id: "the-golden-bird",
    label: "The Golden Bird",
    atuNumber: "ATU 550",
    category: "Tales of Magic",
    emoji: "🪶",
    tagline: "A feather of light, a long road, and a helper who keeps giving good advice.",
  },
  {
    id: "the-water-of-life",
    label: "The Water of Life",
    atuNumber: "ATU 551",
    category: "Tales of Magic",
    emoji: "💧",
    tagline: "A long search for the one thing that will make someone well again.",
  },
  {
    id: "the-fisherman-and-his-wife",
    label: "The Fisherman and His Wife",
    atuNumber: "ATU 555",
    category: "Tales of Magic",
    emoji: "🐟",
    tagline: "A wish-granting fish, a growing list, and the quiet of asking for nothing.",
  },
  {
    id: "the-magic-ring",
    label: "The Magic Ring",
    atuNumber: "ATU 560",
    category: "Tales of Magic",
    emoji: "💍",
    tagline: "A ring that grants help, lost and found by the friends who were paying attention.",
  },
  {
    id: "aladdin",
    label: "Aladdin",
    atuNumber: "ATU 561",
    category: "Tales of Magic",
    emoji: "🪔",
    tagline: "A lamp in a cave, a helper made of smoke, and a wish worth making.",
  },
  {
    id: "the-wishing-table",
    label: "The Wishing-Table",
    atuNumber: "ATU 563",
    category: "Tales of Magic",
    emoji: "🍽️",
    tagline: "A table that lays itself, and the friends who gather round it.",
  },
  {
    id: "the-magic-porridge-pot",
    label: "The Magic Porridge Pot",
    atuNumber: "ATU 565",
    category: "Tales of Magic",
    emoji: "🍲",
    tagline: "A pot that cooks on command, and a village learning the word for stop.",
  },
  {
    id: "the-rabbit-herd",
    label: "The Rabbit Herd",
    atuNumber: "ATU 570",
    category: "Tales of Magic",
    emoji: "🐰",
    tagline: "An impossible job — keep a hundred rabbits together — and a whistle that does it.",
  },
  {
    id: "the-golden-goose",
    label: "The Golden Goose",
    atuNumber: "ATU 571",
    category: "Tales of Magic",
    emoji: "🪿",
    tagline: "A goose of gold, and everyone who touches it stuck fast in a growing parade.",
  },
  {
    id: "spindle-shuttle-and-needle",
    label: "Spindle, Shuttle, and Needle",
    atuNumber: "ATU 585",
    category: "Tales of Magic",
    emoji: "🪡",
    tagline: "Three tools left behind, and the road they make all by themselves.",
  },
  {
    id: "the-princess-and-the-pea",
    label: "The Princess and the Pea",
    atuNumber: "ATU 704",
    category: "Tales of Magic",
    emoji: "🫛",
    tagline: "Twenty mattresses, one small pea, and a very poor night's sleep.",
  },
  {
    id: "the-clever-peasant-girl",
    label: "The Clever Peasant Girl",
    atuNumber: "ATU 875",
    category: "Realistic Tales",
    emoji: "🧠",
    tagline: "Impossible riddles, answered by someone nobody expected to answer them.",
  },
  {
    id: "king-thrushbeard",
    label: "King Thrushbeard",
    atuNumber: "ATU 900",
    category: "Realistic Tales",
    emoji: "🎻",
    tagline: "A sharp tongue, a plain year, and a friendship built on level ground.",
  },
  {
    id: "loving-like-salt",
    label: "Loving Like Salt",
    atuNumber: "ATU 923",
    category: "Realistic Tales",
    emoji: "🧂",
    tagline: "A daughter's odd answer about love, and a supper with no salt in it.",
  },
  {
    id: "lucky-hans",
    label: "Lucky Hans",
    atuNumber: "ATU 1415",
    category: "Anecdotes and Jokes",
    emoji: "🍀",
    tagline: "A trade, and a trade, and a trade, and a man who ends up with nothing and is delighted.",
  },
  {
    id: "castles-in-the-air",
    label: "Castles in the Air",
    atuNumber: "ATU 1430",
    category: "Anecdotes and Jokes",
    emoji: "🏰",
    tagline: "Two daydreamers, one pot of milk, and a fortune spent before it arrives.",
  },
  {
    id: "stone-soup",
    label: "Stone Soup",
    atuNumber: "ATU 1548",
    category: "Anecdotes and Jokes",
    emoji: "🥣",
    tagline: "A stone, a big pot, and a village that turns out to have plenty after all.",
  },
  {
    id: "the-goat-who-wouldnt-go-home",
    label: "The Goat Who Wouldn't Go Home",
    atuNumber: "ATU 2015",
    category: "Formula Tales",
    emoji: "🐐",
    tagline: "A goat who will not budge, and everyone in turn asked to help.",
  },
  {
    id: "the-old-woman-and-her-pig",
    label: "The Old Woman and Her Pig",
    atuNumber: "ATU 2030",
    category: "Formula Tales",
    emoji: "🐖",
    tagline: "A pig that will not cross the stile, and a chain of favours that finally moves.",
  },
  {
    id: "stronger-and-strongest",
    label: "Stronger and Strongest",
    atuNumber: "ATU 2031",
    category: "Formula Tales",
    emoji: "🧱",
    tagline: "Who is the strongest thing in the world? Everyone has a better answer.",
  },
  {
    id: "the-house-that-jack-built",
    label: "The House That Jack Built",
    atuNumber: "ATU 2035",
    category: "Formula Tales",
    emoji: "🏠",
    tagline: "A house, a malt, a rat, a cat — and every verse carries all the ones before.",
  },
  {
    id: "the-enormous-turnip",
    label: "The Enormous Turnip",
    atuNumber: "ATU 2044",
    category: "Formula Tales",
    emoji: "🥬",
    tagline: "A turnip too big to pull, and everyone in the house holding on behind.",
  },
  {
    id: "the-endless-tale",
    label: "The Endless Tale",
    atuNumber: "ATU 2300",
    category: "Formula Tales",
    emoji: "♾️",
    tagline: "A tale with no ending at all, as the sheep go over the wall one at a time.",
  },
];

/** The tale types promoted out of the generated tier, picker-card fields only. */
export const EXTENDED_TALE_TYPE_SUMMARIES: readonly TaleTypeSummary[] = [
  {
    id: "atu-2b-basket-tied-to-wolf-s-tail",
    label: "The Basket on the Wolf's Tail",
    atuNumber: "ATU 2B",
    category: "Animal Tales",
    emoji: "🧺",
    tagline: "A borrowed basket, a wolf's swishing tail, and a fishing trip that goes sideways.",
  },
  {
    id: "atu-5-biting-the-tree-root",
    label: "The Mouse Who Kept On Chewing",
    atuNumber: "ATU 5",
    category: "Animal Tales",
    emoji: "🌱",
    tagline: "A pinched paw, a patient bit of gnawing, and a quiet escape nobody notices.",
  },
  {
    id: "atu-6-animal-captor-persuaded-to-talk",
    label: "The Rooster Who Talked His Way Free",
    atuNumber: "ATU 6",
    category: "Animal Tales",
    emoji: "🐓",
    tagline: "Held gently but firmly, and freed by nothing more than a good question.",
  },
  {
    id: "atu-6-animal-captor-talks-with-booty-in",
    label: "The Bird Who Answered Anyway",
    atuNumber: "ATU 6*",
    category: "Animal Tales",
    emoji: "🐦",
    tagline: "A cheeky remark from the bushes, and a captor who simply cannot help answering back.",
  },
  {
    id: "atu-7-the-three-tree-names",
    label: "The Three Trees' Names",
    atuNumber: "ATU 7",
    category: "Animal Tales",
    emoji: "🌳",
    tagline: "A riddle asked under three different trees, and a friend who has been listening all along.",
  },
  {
    id: "atu-20c-the-animals-flee-in-fear-of",
    label: "Henny-Penny and the Falling Sky",
    atuNumber: "ATU 20C",
    category: "Animal Tales",
    emoji: "🐔",
    tagline: "A tap on the head starts a rumor, a fox offers a shortcut, and a whole feathered line escapes together.",
  },
  {
    id: "atu-31-fox-climbs-from-the-pit-on",
    label: "Out of the Pit, Together",
    atuNumber: "ATU 31",
    category: "Animal Tales",
    emoji: "🕳️",
    tagline: "A deep pit, a boost from an unlikely ladder, and a debt paid back by evening.",
  },
  {
    id: "atu-32-the-wolf-descends-into-the-well",
    label: "Two Buckets in the Well",
    atuNumber: "ATU 32",
    category: "Animal Tales",
    emoji: "🪣",
    tagline: "One bucket down, one bucket up, and a fox who knows exactly how a well works.",
  },
  {
    id: "atu-34-the-wolf-dives-into-the-water",
    label: "The Wolf and the Moon in the Pond",
    atuNumber: "ATU 34",
    category: "Animal Tales",
    emoji: "🌕",
    tagline: "A round pale shape on the water, and a hungry wolf who is sure it's cheese.",
  },
  {
    id: "atu-34a-the-dog-drops-his-meat-for",
    label: "The Dog and the Shadow",
    atuNumber: "ATU 34A",
    category: "Animal Tales",
    emoji: "🐕",
    tagline: "A good piece of meat, a flashy reflection, and a dog who learns that grabbing for more can cost what he already has.",
  },
  {
    id: "atu-34c-the-monkey-with-the-lentils",
    label: "The Monkey and the Lentil",
    atuNumber: "ATU 34C",
    category: "Animal Tales",
    emoji: "🐒",
    tagline: "A handful of lentils, one rolling seed, and a lap that turns out to hold plenty.",
  },
  {
    id: "atu-41-the-wolf-overeats-in-the-cellar",
    label: "The Swollen Fox",
    atuNumber: "ATU 41",
    category: "Animal Tales",
    emoji: "🦊",
    tagline: "A hollow tree full of good things, a gap too narrow for a full belly, and a fox who learns that patience pays off.",
  },
  {
    id: "atu-43-the-bear-builds-a-house-of",
    label: "The House of Wood and the House of Ice",
    atuNumber: "ATU 43",
    category: "Animal Tales",
    emoji: "🏠",
    tagline: "Two neighbours, two houses, and one built to last past the thaw.",
  },
  {
    id: "atu-50a-fox-sees-all-tracks-going-into",
    label: "The Tracks That Never Came Back",
    atuNumber: "ATU 50A",
    category: "Animal Tales",
    emoji: "🐾",
    tagline: "Tracks that only go one way, a fox too clever to be fooled, and a lion who just wanted some company.",
  },
  {
    id: "atu-51a-the-fox-has-the-sniffles",
    label: "The Fox's Sniffles",
    atuNumber: "ATU 51A",
    category: "Animal Tales",
    emoji: "🤧",
    tagline: "A stuffy nose, a ready excuse, and neighbours who see through it kindly.",
  },
  {
    id: "atu-53-the-fox-investigates-a-roar",
    label: "The Fox and the Big Roar",
    atuNumber: "ATU 53*",
    category: "Animal Tales",
    emoji: "🌲",
    tagline: "A tremendous noise in the forest, and one small fox brave enough to check.",
  },
  {
    id: "atu-58-the-crocodile-carries-the-jackal",
    label: "The Crocodile's Ferry",
    atuNumber: "ATU 58",
    category: "Animal Tales",
    emoji: "🐊",
    tagline: "A river crossing, a hungry rumble, and a jackal who talks his way to the far bank.",
  },
  {
    id: "atu-63-the-fox-rids-himself-of-fleas",
    label: "How the Fox Lost His Fleas",
    atuNumber: "ATU 63",
    category: "Animal Tales",
    emoji: "🦊",
    tagline: "An itchy fox, a slow wade into the pond, and a clever way to travel light.",
  },
  {
    id: "atu-67-the-fox-in-a-swollen-river",
    label: "The Fox and the Rising River",
    atuNumber: "ATU 67",
    category: "Animal Tales",
    emoji: "🌊",
    tagline: "A river rising fast, an armful of treasures, and the peace of choosing what to keep.",
  },
  {
    id: "atu-75-the-help-of-the-weak",
    label: "The Lion and the Mouse",
    atuNumber: "ATU 75",
    category: "Animal Tales",
    emoji: "🦁",
    tagline: "A small kindness remembered, and a great favor returned when it matters most.",
  },
  {
    id: "atu-75a-the-lion-and-the-worm",
    label: "The Lion Who Learned to Listen",
    atuNumber: "ATU 75A",
    category: "Animal Tales",
    emoji: "🐛",
    tagline: "A boastful lion, a determined little worm, and a lesson about the smallest creatures.",
  },
  {
    id: "atu-78a-animal-tied-up-because-of-a",
    label: "Tied Safe Through the Storm",
    atuNumber: "ATU 78A",
    category: "Animal Tales",
    emoji: "⛈️",
    tagline: "Dark clouds rolling in, a rope tied to a sturdy tree, and morning arriving calm.",
  },
  {
    id: "atu-81-too-cold-for-hare-to-build",
    label: "Too Busy Enjoying the Weather to Build a House",
    atuNumber: "ATU 81",
    category: "Animal Tales",
    emoji: "❄️",
    tagline: "Four seasons of good excuses, and a warm burrow shared at last.",
  },
  {
    id: "atu-87a-the-bear-stands-on-a-heap",
    label: "The Bear on Top of the World",
    atuNumber: "ATU 87A*",
    category: "Animal Tales",
    emoji: "🪵",
    tagline: "A tall woodpile, a very big claim, and a friendly correction from smaller eyes.",
  },
  {
    id: "atu-111-the-cat-and-the-mouse-converse",
    label: "The Cat and the Mouse Have a Chat",
    atuNumber: "ATU 111",
    category: "Animal Tales",
    emoji: "🐭",
    tagline: "A careful conversation across a very safe distance, and a friendship it grows into.",
  },
  {
    id: "atu-112-the-mice-and-the-rooster",
    label: "The Mice Hold a Meeting",
    atuNumber: "ATU 112**",
    category: "Animal Tales",
    emoji: "🐓",
    tagline: "A cozy council of mice, and a rooster who simply must weigh in.",
  },
  {
    id: "atu-121-wolves-climb-on-top-of-one",
    label: "The Wolves' Wobbly Tower",
    atuNumber: "ATU 121",
    category: "Animal Tales",
    emoji: "🐺",
    tagline: "A basket just out of reach, and a tower of wolves getting wobblier by the minute.",
  },
  {
    id: "atu-122e-wait-for-the-fat-goat",
    label: "The Fox Who Waited for the Fat Goat",
    atuNumber: "ATU 122E",
    category: "Animal Tales",
    emoji: "🐐",
    tagline: "A clever promise of something better later, and a whole afternoon spent waiting for it.",
  },
  {
    id: "atu-152-the-plowman-and-the-animals",
    label: "The Plowman's Fair Day",
    atuNumber: "ATU 152",
    category: "Animal Tales",
    emoji: "🌾",
    tagline: "A big field, a long day, and a fair way to share out the work.",
  },
  {
    id: "atu-158-the-wild-animals-on-the-sleigh",
    label: "Everyone on the Sleigh",
    atuNumber: "ATU 158",
    category: "Animal Tales",
    emoji: "🛷",
    tagline: "A fox with room for one more, and a sleigh piled higher and wobblier by the mile.",
  },
  {
    id: "atu-162-the-master-looks-more-closely-than",
    label: "The Master's Second Look",
    atuNumber: "ATU 162",
    category: "Animal Tales",
    emoji: "👀",
    tagline: "A quick glance that misses everything, and a closer look that catches it all.",
  },
  {
    id: "atu-185-the-nightcap-dealer-and-the-monkeys",
    label: "The Cap Seller and the Monkeys",
    atuNumber: "ATU 185",
    category: "Animal Tales",
    emoji: "🐒",
    tagline: "A whole stack of caps gone missing, and a tree full of copycats to blame.",
  },
  {
    id: "atu-202-the-two-stubborn-goats",
    label: "The Two Goats on the Bridge",
    atuNumber: "ATU 202",
    category: "Animal Tales",
    emoji: "🌉",
    tagline: "Two goats, one narrow bridge, and neither one willing to step back.",
  },
  {
    id: "atu-217-the-cat-with-the-candle",
    label: "The Cat Who Held the Candle",
    atuNumber: "ATU 217",
    category: "Animal Tales",
    emoji: "🕯️",
    tagline: "A candle held perfectly still, and a game of nerves nobody really loses.",
  },
  {
    id: "atu-116-the-bear-on-the-hay-wagon",
    label: "The Bear on the Hay-Wagon",
    atuNumber: "ATU 116",
    category: "Animal Tales",
    emoji: "🐻",
    tagline: "A tired bear, a slow-rolling hay-wagon, and a ride home nobody planned on.",
  },
  {
    id: "atu-122c-the-sheep-persuades-the-wolf-to",
    label: "The Kid Who Asked the Wolf to Sing",
    atuNumber: "ATU 122C",
    category: "Animal Tales",
    emoji: "🐐",
    tagline: "A wandering kid, a request for one last song, and a wolf too vain to refuse.",
  },
  {
    id: "atu-135-the-mouse-makes-a-boat-of",
    label: "The Mouse's Bread-Crust Boat",
    atuNumber: "ATU 135*",
    category: "Animal Tales",
    emoji: "🐭",
    tagline: "A crumb of crust, a hollowed-out hull, and a little sailor bound downstream.",
  },
  {
    id: "atu-156a-the-faith-of-the-lion",
    label: "The Lion Who Remembered a Kindness",
    atuNumber: "ATU 156A",
    category: "Animal Tales",
    emoji: "🦁",
    tagline: "A thorn pulled free in the forest, and a debt a lion never once forgot.",
  },
  {
    id: "atu-159-straw-bull",
    label: "The Straw Bull in the Field",
    atuNumber: "ATU 159",
    category: "Animal Tales",
    emoji: "🐂",
    tagline: "A bull of straw and tar, standing perfectly still, and a lesson about sticking too close.",
  },
  {
    id: "atu-163-the-singing-wolf",
    label: "The Wolf Who Would Rather Sing",
    atuNumber: "ATU 163",
    category: "Animal Tales",
    emoji: "🎶",
    tagline: "A wolf who loves his own voice more than any errand, and neighbors who use that against him kindly.",
  },
  {
    id: "atu-186-the-monkey-and-the-nut",
    label: "The Monkey and the Stubborn Nut",
    atuNumber: "ATU 186",
    category: "Animal Tales",
    emoji: "🥥",
    tagline: "A shell too hard for force, and a monkey who finally tries patience instead.",
  },
  {
    id: "atu-214-the-donkey-tries-to-caress-his",
    label: "The Donkey Who Wanted to Be a Lapdog",
    atuNumber: "ATU 214",
    category: "Animal Tales",
    emoji: "🫏",
    tagline: "A hardworking donkey, a pampered little dog, and a clumsy try at trading places.",
  },
  {
    id: "atu-120-the-first-to-see-the-sunrise",
    label: "Who Sees the Sunrise First?",
    atuNumber: "ATU 120",
    category: "Animal Tales",
    emoji: "🌄",
    tagline: "A meadow full of animals facing east, and one who thinks to look somewhere else entirely.",
  },
  {
    id: "atu-122d-caught-animal-promises-captor-better-prey",
    label: "The Promise of a Fatter Supper",
    atuNumber: "ATU 122D",
    category: "Animal Tales",
    emoji: "🐑",
    tagline: "A hungry captor, a very convincing promise, and a meal that is never quite over the hill.",
  },
  {
    id: "atu-135a-the-fox-stumbles-over-a-violin",
    label: "The Fox and the Singing Box",
    atuNumber: "ATU 135A*",
    category: "Animal Tales",
    emoji: "🎻",
    tagline: "A dark barn, an unexpected twang, and a fox convinced the night has come alive.",
  },
  {
    id: "atu-157b-the-sparrow-and-his-sons",
    label: "The Sparrow's Warnings",
    atuNumber: "ATU 157B",
    category: "Animal Tales",
    emoji: "🐦",
    tagline: "A father's careful list of dangers, and sons who mostly, but not perfectly, remember it.",
  },
  {
    id: "atu-159c-the-lion-and-the-statue",
    label: "The Lion and the Carved Statue",
    atuNumber: "ATU 159C",
    category: "Animal Tales",
    emoji: "🦁",
    tagline: "Two friends arguing over who is stronger, and a carving that only tells one side of it.",
  },
  {
    id: "atu-183-the-hare-promises-to-dance",
    label: "The Hare Who Promised to Dance",
    atuNumber: "ATU 183*",
    category: "Animal Tales",
    emoji: "🐇",
    tagline: "A grand promise, a gathered crowd, and a dancer who needs a little coaxing to actually begin.",
  },
  {
    id: "atu-200a-the-dog-loses-a-certificate",
    label: "The Dog's Missing Paper",
    atuNumber: "ATU 200A",
    category: "Animal Tales",
    emoji: "📜",
    tagline: "An important paper gone missing, and a search that turns into something better than finding it.",
  },
  {
    id: "atu-214b-the-donkey-in-lion-s-skin",
    label: "The Donkey in the Lion's Coat",
    atuNumber: "ATU 214B",
    category: "Animal Tales",
    emoji: "🦁",
    tagline: "A borrowed lion's coat, a great deal of swagger, and one small bray that gives it all away.",
  },
  {
    id: "atu-218-a-cat-transformed-to-a-maiden",
    label: "The Cat Who Became a Girl",
    atuNumber: "ATU 218",
    category: "Animal Tales",
    emoji: "🐱",
    tagline: "A wish granted, a wedding day, and one small mouse that gives the game away.",
  },
  {
    id: "atu-233b-the-birds-fly-off-with-the",
    label: "The Birds Who Flew Off with the Net",
    atuNumber: "ATU 233B",
    category: "Animal Tales",
    emoji: "🕸️",
    tagline: "One net, dozens of little birds, and a plan that only works if everybody lifts together.",
  },
  {
    id: "atu-244-the-raven-in-borrowed-feathers",
    label: "The Bird in Borrowed Feathers",
    atuNumber: "ATU 244",
    category: "Animal Tales",
    emoji: "🪶",
    tagline: "Borrowed feathers, a grand entrance, and friends who help him find his own shine.",
  },
  {
    id: "atu-299-the-mountain-gives-birth-to-a",
    label: "The Mountain and the Tiny Mouse",
    atuNumber: "ATU 299",
    category: "Animal Tales",
    emoji: "⛰️",
    tagline: "The whole valley holds its breath for the mountain's big surprise, and gets a small one instead.",
  },
  {
    id: "atu-476-coal-turns-into-gold",
    label: "The Coal That Turned to Gold",
    atuNumber: "ATU 476",
    category: "Tales of Magic",
    emoji: "✨",
    tagline: "A stranger's odd gift, a pocket forgotten overnight, and a fortune nobody expected.",
  },
  {
    id: "atu-735-the-rich-man-s-and-the",
    label: "The Rich Man's Luck and the Poor Man's Luck",
    atuNumber: "ATU 735",
    category: "Tales of Magic",
    emoji: "🍞",
    tagline: "Two neighbors, two very different piles of luck, and a lesson about what people do with what they're given.",
  },
  {
    id: "atu-759e-the-miller-of-sans-souci",
    label: "The Miller Who Would Not Sell",
    atuNumber: "ATU 759E",
    category: "Religious Tales",
    emoji: "🌾",
    tagline: "A king wants a view, a miller wants his mill, and both get to keep what matters most.",
  },
  {
    id: "atu-887a-precious-stones-in-bricks",
    label: "The Treasure in the Bricks",
    atuNumber: "ATU 887A*",
    category: "Realistic Tales",
    emoji: "🧱",
    tagline: "A plain little house, a curious buyer, and bricks that turn out to hold more than mortar.",
  },
  {
    id: "atu-920b-the-birds-chosen-by-the-sons",
    label: "The Birds the Brothers Chose",
    atuNumber: "ATU 920B",
    category: "Realistic Tales",
    emoji: "🦅",
    tagline: "Three brothers, three birds, and a father who learns exactly who each son is by what he picks.",
  },
  {
    id: "atu-923a-like-wind-in-the-hot-sun",
    label: "Loved Like the Wind on a Hot Day",
    atuNumber: "ATU 923A",
    category: "Realistic Tales",
    emoji: "🍃",
    tagline: "A father asks how much he is loved, and the strangest answer turns out to be the truest.",
  },
  {
    id: "atu-944-king-for-a-year",
    label: "King for a Year",
    atuNumber: "ATU 944",
    category: "Realistic Tales",
    emoji: "👑",
    tagline: "A whole year on the throne, a wise plan for what comes after, and a kingdom left better for it.",
  },
  {
    id: "atu-2010a-the-twelve-days-of-christmas",
    label: "The Twelve Days of Gifts",
    atuNumber: "ATU 2010A",
    category: "Formula Tales",
    emoji: "🎁",
    tagline: "One gift a day, piling higher and higher, until the list becomes half the fun of singing it.",
  },
  {
    id: "atu-219f-the-dog-and-the-sow-argue",
    label: "The Dog and the Sow's Big Argument",
    atuNumber: "ATU 219F*",
    category: "Animal Tales",
    emoji: "🐷",
    tagline: "A friendly dog, a proud sow, and a small argument about whose babies are best.",
  },
  {
    id: "atu-233d-the-birds-and-the-fowler",
    label: "The Birds Who Outsmarted the Fowler",
    atuNumber: "ATU 233D",
    category: "Animal Tales",
    emoji: "🐦",
    tagline: "A net full of seed, a patient fowler, and a flock too clever to fall for it.",
  },
  {
    id: "atu-253-the-fish-in-the-net",
    label: "The Fish Who Told the Tale",
    atuNumber: "ATU 253",
    category: "Animal Tales",
    emoji: "🐟",
    tagline: "A fish slips free of the net, and the story only grows taller with every telling.",
  },
  {
    id: "atu-302c-the-magic-horse",
    label: "The Horse Who Waited for the Right Rider",
    atuNumber: "ATU 302C*",
    category: "Tales of Magic",
    emoji: "🐴",
    tagline: "A horse with a secret gift, patiently waiting for someone kind enough to earn it.",
  },
  {
    id: "atu-513b-the-land-and-water-ship",
    label: "The Ship That Sailed on Land",
    atuNumber: "ATU 513B",
    category: "Tales of Magic",
    emoji: "⛵",
    tagline: "A kind-hearted traveler, a little grey stranger, and a ship that glides over fields as easily as waves.",
  },
  {
    id: "atu-736-luck-and-wealth",
    label: "The Argument Between Luck and Wealth",
    atuNumber: "ATU 736",
    category: "Tales of Magic",
    emoji: "🍀",
    tagline: "Luck and Wealth cannot agree which of them truly runs a person's life.",
  },
  {
    id: "atu-775-midas-short-sighted-wish",
    label: "The King Whose Touch Turned Everything to Gold",
    atuNumber: "ATU 775",
    category: "Religious Tales",
    emoji: "👑",
    tagline: "A wish for a golden touch turns out to be much less delicious than it sounds.",
  },
  {
    id: "atu-910-the-clever-precepts",
    label: "The Three Pieces of Advice",
    atuNumber: "ATU 910",
    category: "Realistic Tales",
    emoji: "📜",
    tagline: "Three small pieces of advice, each one seemingly useless, until the exact right moment.",
  },
  {
    id: "atu-920e-the-three-rings",
    label: "The Father's Three Rings",
    atuNumber: "ATU 920E",
    category: "Realistic Tales",
    emoji: "💍",
    tagline: "Three identical rings, one father, and three children who each feel truly chosen.",
  },
  {
    id: "atu-924-discussion-in-sign-language",
    label: "The Great Silent Argument",
    atuNumber: "ATU 924",
    category: "Realistic Tales",
    emoji: "🤚",
    tagline: "A whole debate carried out in hand signs, with both sides sure they've won.",
  },
  {
    id: "atu-944-easy-come-easy-go",
    label: "The Fortune That Came and Went",
    atuNumber: "ATU 944*",
    category: "Realistic Tales",
    emoji: "🪙",
    tagline: "A sudden fortune arrives through good luck, and slips away just as easily.",
  },
  {
    id: "atu-2010i-how-the-rich-man-paid-his",
    label: "The Servant's Clever Payment",
    atuNumber: "ATU 2010I",
    category: "Formula Tales",
    emoji: "🔁",
    tagline: "A rich man tries to pay his servant a single coin, and the joke just keeps rolling.",
  },
  {
    id: "atu-219h-the-rooster-and-the-pearl",
    label: "The Rooster and the Pearl",
    atuNumber: "ATU 219H*",
    category: "Animal Tales",
    emoji: "🐓",
    tagline: "A shiny find in the dirt, and a rooster who'd much rather have breakfast.",
  },
  {
    id: "atu-235-the-jay-borrows-the-cuckoo-s",
    label: "The Jay in the Cuckoo's Feathers",
    atuNumber: "ATU 235",
    category: "Animal Tales",
    emoji: "🪶",
    tagline: "A borrowed coat of feathers, and a jay who learns his own suit him better.",
  },
  {
    id: "atu-275a-the-race-between-hare-and-tortoise",
    label: "The Hare and the Tortoise",
    atuNumber: "ATU 275A",
    category: "Animal Tales",
    emoji: "🐢",
    tagline: "A boastful hare, a patient tortoise, and a race decided by steady feet.",
  },
  {
    id: "atu-369-the-youth-on-a-quest-for",
    label: "The Boy Who Went to Find His Father",
    atuNumber: "ATU 369",
    category: "Tales of Magic",
    emoji: "🌅",
    tagline: "A boy who has never met his father sets out to find him, with something to prove along the way.",
  },
  {
    id: "atu-515-the-shepherd-boy",
    label: "The Shepherd Boy and the King's Questions",
    atuNumber: "ATU 515",
    category: "Tales of Magic",
    emoji: "🐑",
    tagline: "A king with three riddling questions, and a shepherd boy with nothing but plain good sense.",
  },
  {
    id: "atu-739-the-luck-bringing-animal",
    label: "The Animal Who Brought Luck",
    atuNumber: "ATU 739*",
    category: "Tales of Magic",
    emoji: "🍀",
    tagline: "A stray creature taken in out of kindness, and the good fortune that follows it home.",
  },
  {
    id: "atu-779h-star-money",
    label: "Star Money",
    atuNumber: "ATU 779H*",
    category: "Religious Tales",
    emoji: "⭐",
    tagline: "A girl with nothing left to give away, and stars that fall like coins into her apron.",
  },
  {
    id: "atu-910e-find-the-treasure-in-our-vineyard",
    label: "The Treasure in the Vineyard",
    atuNumber: "ATU 910E",
    category: "Realistic Tales",
    emoji: "🍇",
    tagline: "A father's dying wish, a hidden treasure, and sons who dig their way to a very different kind of riches.",
  },
  {
    id: "atu-921a-the-sharing-of-bread-or-money",
    label: "The Fairest Way to Share",
    atuNumber: "ATU 921A",
    category: "Realistic Tales",
    emoji: "🍞",
    tagline: "Two hungry travellers, one loaf of bread, and a clever way to split it fair.",
  },
  {
    id: "atu-925-the-most-beautiful-in-the-garden",
    label: "The Most Beautiful Thing in the Garden",
    atuNumber: "ATU 925*",
    category: "Realistic Tales",
    emoji: "🌻",
    tagline: "A garden full of contenders for 'most beautiful,' and an answer nobody expected.",
  },
  {
    id: "atu-945-luck-and-intelligence",
    label: "Luck and Intelligence",
    atuNumber: "ATU 945",
    category: "Realistic Tales",
    emoji: "🎲",
    tagline: "Luck and Intelligence set off to see who gets further, and end up needing each other.",
  },
  {
    id: "atu-2010ia-the-animals-with-peculiar-names",
    label: "The House of Peculiar Names",
    atuNumber: "ATU 2010IA",
    category: "Formula Tales",
    emoji: "🐐",
    tagline: "A houseful of animals with names too silly to remember, and a bedtime rhyme that finally sticks.",
  },
  {
    id: "atu-220-the-council-of-birds",
    label: "The Grand Council of the Birds",
    atuNumber: "ATU 220",
    category: "Animal Tales",
    emoji: "🦉",
    tagline: "Every bird in the forest gets a turn to speak, smallest first.",
  },
  {
    id: "atu-235c-a-bird-has-new-clothes-made",
    label: "The Bird's Backward Coat",
    atuNumber: "ATU 235C*",
    category: "Animal Tales",
    emoji: "🪡",
    tagline: "A brand-new coat, and a bird who cannot decide which way is front.",
  },
  {
    id: "atu-276-the-crab-walks-backward-learned-from",
    label: "The Crab Who Learned by Watching",
    atuNumber: "ATU 276",
    category: "Animal Tales",
    emoji: "🦀",
    tagline: "A mother tells her son to walk straight, and then tries it herself.",
  },
  {
    id: "atu-408-the-three-oranges",
    label: "The Prince and the Three Oranges",
    atuNumber: "ATU 408",
    category: "Tales of Magic",
    emoji: "🍊",
    tagline: "Three golden oranges, each holding something more wonderful than the last.",
  },
  {
    id: "atu-517-the-boy-who-understands-the-language",
    label: "The Boy Who Understood the Birds",
    atuNumber: "ATU 517",
    category: "Tales of Magic",
    emoji: "🕊️",
    tagline: "A boy who understands what the birds are saying, and is careful who he tells.",
  },
  {
    id: "atu-745-hatch-penny",
    label: "The Coin That Always Came Home",
    atuNumber: "ATU 745",
    category: "Tales of Magic",
    emoji: "🪙",
    tagline: "A single small coin that will not stay lost, however often it is spent.",
  },
  {
    id: "atu-821b-chickens-from-boiled-eggs",
    label: "The Wise Answer About Boiled Eggs",
    atuNumber: "ATU 821B",
    category: "Religious Tales",
    emoji: "🥚",
    tagline: "Boiled eggs will not hatch chickens, and a kind hostess proves it gently.",
  },
  {
    id: "atu-910f-the-quarreling-sons-and-the-bundle",
    label: "The Bundle of Sticks",
    atuNumber: "ATU 910F",
    category: "Realistic Tales",
    emoji: "🥢",
    tagline: "One twig snaps easily; the whole bundle will not break at all.",
  },
  {
    id: "atu-921b-best-friend-worst-enemy",
    label: "The Best Friend and the Worst Enemy",
    atuNumber: "ATU 921B",
    category: "Realistic Tales",
    emoji: "💬",
    tagline: "Who is the best friend and who the worst enemy, and both answers are the same.",
  },
  {
    id: "atu-927a-old-saddle-granted-by-the-king",
    label: "The Old Saddle the King Gave Away",
    atuNumber: "ATU 927A*",
    category: "Realistic Tales",
    emoji: "🐎",
    tagline: "An old saddle, granted by the king, worth far more than it appears.",
  },
  {
    id: "atu-945a-money-and-fortune",
    label: "Money and Good Fortune",
    atuNumber: "ATU 945A*",
    category: "Realistic Tales",
    emoji: "🍀",
    tagline: "Money and fortune, and the discovery that they are not the same thing.",
  },
  {
    id: "atu-2016-wee-wee-woman",
    label: "The Wee Wee Woman's Wee Wee House",
    atuNumber: "ATU 2016",
    category: "Formula Tales",
    emoji: "🏠",
    tagline: "A wee wee woman in a wee wee house, and everything just as small as she is.",
  },
  {
    id: "atu-224-bird-wedding",
    label: "The Bird Wedding",
    atuNumber: "ATU 224",
    category: "Animal Tales",
    emoji: "🪶",
    tagline: "A wedding day for the whole flock, with feathers for ribbons and a song for a cake.",
  },
  {
    id: "atu-236-the-magpie-teaches-the-dove-to",
    label: "The Magpie's Nest",
    atuNumber: "ATU 236",
    category: "Animal Tales",
    emoji: "🥚",
    tagline: "The cleverest builder in the meadow teaches a lesson that only one listener stays to finish.",
  },
  {
    id: "atu-278a-frogs-decide-not-to-jump-into",
    label: "The Frogs and the Well",
    atuNumber: "ATU 278A*",
    category: "Animal Tales",
    emoji: "🐸",
    tagline: "A dried-up marsh, a tempting well, and one frog wise enough to ask a question first.",
  },
  {
    id: "atu-426-the-two-girls-the-bear-and",
    label: "The Two Sisters and the Winter Bear",
    atuNumber: "ATU 426",
    category: "Tales of Magic",
    emoji: "🐻",
    tagline: "Two devoted sisters, a shivering bear at the door, and a kindness that turns out to matter more than they knew.",
  },
  {
    id: "atu-554-the-grateful-animals",
    label: "The Grateful Animals",
    atuNumber: "ATU 554",
    category: "Tales of Magic",
    emoji: "🐜",
    tagline: "Small kindnesses to fish, ants, and birds along the road, each one paid back exactly when it's needed most.",
  },
  {
    id: "atu-745a-the-predestined-treasure",
    label: "The Treasure That Was Waiting",
    atuNumber: "ATU 745A",
    category: "Tales of Magic",
    emoji: "💰",
    tagline: "A poor man given away a fortune he doesn't yet know is his, and a treasure patient enough to wait for him.",
  },
  {
    id: "atu-842c-floating-coins",
    label: "The Coins That Would Not Sink",
    atuNumber: "ATU 842C*",
    category: "Religious Tales",
    emoji: "🪙",
    tagline: "A handful of coins tossed into the stream, and the honest hand they drift toward instead of sinking.",
  },
  {
    id: "atu-910g-man-buys-a-pennyworth-of-wit",
    label: "The Pennyworth of Wisdom",
    atuNumber: "ATU 910G",
    category: "Realistic Tales",
    emoji: "🪙",
    tagline: "A single coin spent on advice, and a small piece of wisdom that turns out to be worth far more.",
  },
  {
    id: "atu-921c-why-hair-of-head-is-gray",
    label: "Why Hair Turns Gray First",
    atuNumber: "ATU 921C",
    category: "Realistic Tales",
    emoji: "🧔",
    tagline: "A king's riddle about hair and beards, and a clever answer nobody else thought to give.",
  },
  {
    id: "atu-928-planting-for-the-next-generation",
    label: "The Trees He Would Never Sit Under",
    atuNumber: "ATU 928",
    category: "Realistic Tales",
    emoji: "🌳",
    tagline: "An old man planting saplings for shade he will never enjoy, and the young stranger who asks him why.",
  },
  {
    id: "atu-967-the-man-saved-by-a-spider",
    label: "The Spider at the Cave Mouth",
    atuNumber: "ATU 967",
    category: "Realistic Tales",
    emoji: "🕸️",
    tagline: "A traveler hiding from searchers, and a spider who spins just the right web at just the right moment.",
  },
  {
    id: "atu-2031a-the-esdras-chain-stronger-and-strongest",
    label: "Stronger and Strongest",
    atuNumber: "ATU 2031A",
    category: "Formula Tales",
    emoji: "🔗",
    tagline: "A mouse asks who is strongest in all the world, and the answer chains from one surprising thing to the next.",
  },
  {
    id: "atu-230-the-race-of-the-rooster-the",
    label: "The Great Heather Race",
    atuNumber: "ATU 230*",
    category: "Animal Tales",
    emoji: "🐓",
    tagline: "A boastful rooster, two quick moor-birds, and a race that ends in a laugh, not a loser.",
  },
  {
    id: "atu-238-the-dove-and-the-frog-boast",
    label: "The Dove and the Frog",
    atuNumber: "ATU 238",
    category: "Animal Tales",
    emoji: "🕊️",
    tagline: "A treetop nest, a lily-pad pond, and two friends each sure their home is the finest.",
  },
  {
    id: "atu-280-the-ant-carries-a-load-as",
    label: "The Ant's Enormous Crumb",
    atuNumber: "ATU 280",
    category: "Animal Tales",
    emoji: "🐜",
    tagline: "A crumb far bigger than she is, and one small ant who never once complains.",
  },
  {
    id: "atu-430-the-donkey",
    label: "The Prince in Donkey's Coat",
    atuNumber: "ATU 430",
    category: "Tales of Magic",
    emoji: "🎻",
    tagline: "A prince born in an unlikely shape, and a household that learns to see past it.",
  },
  {
    id: "atu-570a-the-princess-and-the-magic-shell",
    label: "The Shell That Held the Sea",
    atuNumber: "ATU 570A",
    category: "Tales of Magic",
    emoji: "🐚",
    tagline: "A shell that hums with the whole ocean, and a princess who learns to listen closely.",
  },
  {
    id: "atu-752b-the-forgotten-wind",
    label: "The Wind Everyone Forgot to Thank",
    atuNumber: "ATU 752B",
    category: "Religious Tales",
    emoji: "🍃",
    tagline: "A village that thanks the sun and the rain every harvest, and a wind that simply wants to be remembered.",
  },
  {
    id: "atu-844-the-luck-bringing-shirt",
    label: "The Happiest Man's Shirt",
    atuNumber: "ATU 844",
    category: "Religious Tales",
    emoji: "👕",
    tagline: "A restless king, a search for happiness, and a shepherd who owns nothing but contentment.",
  },
  {
    id: "atu-915-all-depends-on-how-you-take",
    label: "Good News, Bad News",
    atuNumber: "ATU 915",
    category: "Realistic Tales",
    emoji: "🌾",
    tagline: "The same news, taken two ways, and a farmer who never rushes to decide which.",
  },
  {
    id: "atu-921c-astronomer-and-doctor-at-farmer-s",
    label: "The Stargazer, the Doctor, and the Farmer's Supper",
    atuNumber: "ATU 921C*",
    category: "Realistic Tales",
    emoji: "🔭",
    tagline: "Two learned travelers arguing over supper, and a farmer whose plain answer beats them both.",
  },
  {
    id: "atu-935-the-prodigal-s-return",
    label: "The Long Way Home",
    atuNumber: "ATU 935",
    category: "Realistic Tales",
    emoji: "🏡",
    tagline: "A long way from home, and a door left open the whole time.",
  },
  {
    id: "atu-983-the-dishes-of-the-same-flavor",
    label: "Ten Dishes, One Flavor",
    atuNumber: "ATU 983",
    category: "Realistic Tales",
    emoji: "🍲",
    tagline: "A cook, a king who wants nothing but his favorite spice, and a supper that makes the point for her.",
  },
  {
    id: "atu-2034-the-mouse-regains-its-tail",
    label: "The Mouse Who Wanted Her Tail Back",
    atuNumber: "ATU 2034",
    category: "Formula Tales",
    emoji: "🐭",
    tagline: "A tail held fast, a chain of small favors, and neighbors who all keep their word.",
  },
  {
    id: "atu-232-the-birch-cock-and-the-birds",
    label: "The Bird Who Chose to Stay",
    atuNumber: "ATU 232",
    category: "Animal Tales",
    emoji: "🐦",
    tagline: "The travelling flocks call him south, but one small bird likes his own birch tree best.",
  },
  {
    id: "atu-239-the-crow-helps-the-deer-escape",
    label: "The Crow's Warning Call",
    atuNumber: "ATU 239",
    category: "Animal Tales",
    emoji: "🦌",
    tagline: "A hidden snare in the grass, and a sharp-eyed crow who won't stop calling until her friend understands.",
  },
  {
    id: "atu-282b-conversation-of-fly-and-flea",
    label: "The Fly and the Flea's Big Chat",
    atuNumber: "ATU 282B*",
    category: "Animal Tales",
    emoji: "🪰",
    tagline: "A fly, a flea, and an evening that turns into the longest conversation either has ever had.",
  },
  {
    id: "atu-442-the-old-woman-in-the-forest",
    label: "The Kind Woman of the Forest",
    atuNumber: "ATU 442",
    category: "Tales of Magic",
    emoji: "🌲",
    tagline: "A girl lost among the trees finds a small dove to help, and the forest finds a way to thank her.",
  },
  {
    id: "atu-681-relativity-of-time",
    label: "The Afternoon That Lasted a Hundred Years",
    atuNumber: "ATU 681",
    category: "Tales of Magic",
    emoji: "⏳",
    tagline: "A king steps into an enchanted garden for what feels like a single afternoon, and returns to find the whole world has quietly moved on.",
  },
  {
    id: "atu-754-lucky-poverty",
    label: "The Luckiest Little House in the Valley",
    atuNumber: "ATU 754",
    category: "Religious Tales",
    emoji: "🍞",
    tagline: "A family with almost nothing to their name, and a small kindness that shows they had everything they needed.",
  },
  {
    id: "atu-875b-the-clever-girl-and-the-king",
    label: "The Girl Who Answered Every Riddle",
    atuNumber: "ATU 875B",
    category: "Realistic Tales",
    emoji: "👑",
    tagline: "A king with a trickier riddle every day, and a farmer's daughter who never once runs out of answers.",
  },
  {
    id: "atu-915a-the-misunderstood-precepts",
    label: "The Advice Taken Exactly at Its Word",
    atuNumber: "ATU 915A",
    category: "Realistic Tales",
    emoji: "📜",
    tagline: "Three pieces of good advice, followed to the very letter, and a young traveller who learns their true meaning the hard way.",
  },
  {
    id: "atu-921e-never-heard-before",
    label: "The Answer Nobody Had Heard",
    atuNumber: "ATU 921E",
    category: "Realistic Tales",
    emoji: "💬",
    tagline: "A king's court full of clever answers, and one small voice with something truly new to say.",
  },
  {
    id: "atu-936-the-golden-mountain",
    label: "The Long Climb Up the Golden Mountain",
    atuNumber: "ATU 936*",
    category: "Realistic Tales",
    emoji: "⛰️",
    tagline: "A mountain said to be made of gold, and a slow, steady climb that turns out to matter more than the treasure.",
  },
  {
    id: "atu-987-false-magician-exposed-by-clever-girl",
    label: "The Girl Who Saw Through the Magic Show",
    atuNumber: "ATU 987",
    category: "Realistic Tales",
    emoji: "🎩",
    tagline: "A magician's dazzling tricks amaze the whole village, except for one girl who simply keeps watching.",
  },
  {
    id: "atu-2039-the-horseshoe-nail",
    label: "The Nail That Nearly Wasn't There",
    atuNumber: "ATU 2039",
    category: "Formula Tales",
    emoji: "🔨",
    tagline: "One tiny missing nail, and a gentle chain of small troubles that follows all the way home.",
  },
  {
    id: "atu-232d-a-crow-drops-pebbles-into-a",
    label: "The Crow and the Rising Water",
    atuNumber: "ATU 232D*",
    category: "Animal Tales",
    emoji: "🐦‍⬛",
    tagline: "A thirsty crow, a jug too narrow to sip from, and a slow, clever fix.",
  },
  {
    id: "atu-240-the-dove-trades-her-eggs",
    label: "The Dove Who Wanted Different Eggs",
    atuNumber: "ATU 240",
    category: "Animal Tales",
    emoji: "🕊️",
    tagline: "A dove convinced someone else's nest must hold better eggs than her own.",
  },
  {
    id: "atu-298c-the-reeds-bend-before-wind",
    label: "The Oak and the Bending Reeds",
    atuNumber: "ATU 298C*",
    category: "Animal Tales",
    emoji: "🌾",
    tagline: "A mighty oak learns the storm was never a fight to win by standing rigid.",
  },
  {
    id: "atu-465-go-i-know-not-whither-and",
    label: "Fetch I-Know-Not-What",
    atuNumber: "ATU 465",
    category: "Tales of Magic",
    emoji: "🧭",
    tagline: "An impossible errand for a nameless thing, solved by kindness along the way.",
  },
  {
    id: "atu-715a-the-wonderful-rooster",
    label: "The Rooster's Golden Crow",
    atuNumber: "ATU 715A",
    category: "Tales of Magic",
    emoji: "🐓",
    tagline: "A humble rooster whose ordinary crowing hides an extraordinary secret.",
  },
  {
    id: "atu-756e-charity-rewarded",
    label: "The Kindness That Came Back Around",
    atuNumber: "ATU 756E*",
    category: "Religious Tales",
    emoji: "🍞",
    tagline: "A small act of giving, offered without expecting anything back.",
  },
  {
    id: "atu-875e-the-unjust-decision-the-oil-press",
    label: "The Clever Answer to an Odd Question",
    atuNumber: "ATU 875E",
    category: "Realistic Tales",
    emoji: "⚖️",
    tagline: "A silly ruling gets answered with an even sillier question, and everyone learns something.",
  },
  {
    id: "atu-920a-the-case-of-the-boiled-eggs",
    label: "The Riddle of the Boiled Eggs",
    atuNumber: "ATU 920A",
    category: "Realistic Tales",
    emoji: "🥚",
    tagline: "A stubborn old debt argued back into good sense with one perfect riddle.",
  },
  {
    id: "atu-922b-the-king-s-face-on-the",
    label: "Whose Face Belongs on the Coin",
    atuNumber: "ATU 922B",
    category: "Realistic Tales",
    emoji: "🪙",
    tagline: "A puzzling royal question about coins, answered with plain good sense.",
  },
  {
    id: "atu-940-the-forgiven-debt",
    label: "The Debt Let Go",
    atuNumber: "ATU 940*",
    category: "Realistic Tales",
    emoji: "📜",
    tagline: "An old debt quietly forgiven, and the peace that settles in after.",
  },
  {
    id: "atu-2009-origin-of-chess",
    label: "One Grain on the First Square",
    atuNumber: "ATU 2009",
    category: "Formula Tales",
    emoji: "♟️",
    tagline: "A wise inventor asks for the humblest reward, and the numbers grow wonderfully huge.",
  },
  {
    id: "atu-2301-corn-carried-away-one-grain-at",
    label: "One Grain at a Time",
    atuNumber: "ATU 2301",
    category: "Formula Tales",
    emoji: "🌽",
    tagline: "A patient little creature carries away a mountain of corn, one grain at a time, for as long as you like.",
  },
];

/** Every featured tale type, picker-card fields only. */
export const TALE_TYPE_SUMMARIES: readonly TaleTypeSummary[] = [
  ...ORIGINAL_TALE_TYPE_SUMMARIES,
  ...CURATED_TALE_TYPE_SUMMARIES,
  ...EXTENDED_TALE_TYPE_SUMMARIES,
];
