/**
 * Beats for the 50 tale types that used to be catalogue-only.
 *
 * These are the ones a parent actually recognises — Jack and the Beanstalk,
 * Rapunzel, Stone Soup, The Enormous Turnip. Until now each drove the prompt
 * with a single blurb line while the original twelve drove it with beats,
 * signature elements, tone and an opener. This file closes that gap; the
 * featured tier goes from 12 to 62.
 *
 * ## Written as the gentle telling, not the faithful one
 *
 * The traditional versions of several of these do not survive contact with
 * `SYSTEM_PROMPT`. Rapunzel's prince falls into thorns and is blinded. The
 * Fisherman's Wife ends in a storm and a hovel. The Fox and the Crow ends with
 * the crow humiliated and the fox laughing, and the app promises that nobody is
 * humiliated. The Three Little Pigs traditionally ends with a wolf in a pot.
 *
 * So the beats describe the telling this app would produce anyway. Writing them
 * faithfully and leaving the storyteller to soften them at generation time
 * would only set the brief arguing with the safety rules — and the brief would
 * lose, less predictably. The crow keeps her dignity here, the wolf is given
 * soup at the door, and the last beat of every set lands somewhere warm and
 * still, because that is where the wind-down arc has to finish.
 *
 * ## No source text, because no source text was ever fetched
 *
 * The plan for this file was to download the public-domain collections (Grimm,
 * Aesop, Jacobs, Andersen) and derive each structural digest from the text.
 * That is not what happened: these fifty are famous enough that their shapes
 * were written from knowledge of the tales, and no Gutenberg text was retrieved
 * or stored.
 *
 * Which makes the "nothing is quoted" guarantee stronger than planned rather
 * than weaker — there was no source in front of anyone to quote from — but it
 * is a different guarantee, so it is written down here rather than glossed. It
 * also means these beats carry the ordinary risk of writing from memory: a
 * detail may be wrong in a way reading the text would have caught. They are
 * checked against the shape of the tale, not against an edition.
 *
 * Every `exampleOpener` is newly written, exactly as the original twelve are,
 * and no source text reaches the prompt or the browser.
 */

import type { TaleType } from "./tale-types";

/** The 50 formerly catalogue-only types, now with beats. */
export const CURATED_TALE_TYPES: readonly TaleType[] = [
  {
    id: "how-the-bear-lost-his-tail",
    label: "How the Bear Lost His Tail",
    atuNumber: "ATU 2",
    category: "Animal Tales",
    emoji: "🐻",
    tagline: "A long tail, a frozen lake, and a lesson learned the chilly way.",
    beats: [
      "A bear with a long, magnificent tail meets a fox carrying a string of fish",
      "The fox says the fish came from a hole in the ice, caught by dangling a tail",
      "The bear sits down on the ice and waits, and waits, through a long still night",
      "Dawn comes, the bear stands up, and his tail stays behind in the ice",
      "The fox is sorry, the bear finds he does not mind, and the two walk home along a pink and quiet shore",
    ],
    signatureElements: [
      "a proud bear with a splendid tail",
      "a fox with a story to tell",
      "a hole in the ice under a wide sky",
      "a short tail carried without regret",
    ],
    tone: "wry, wintry, and forgiving",
    exampleOpener:
      "In the days when bears had tails like brooms, one bear sat down on the ice to fish, and the stars came out to keep him company.",
  },
  {
    id: "the-fox-and-the-crow",
    label: "The Fox and the Crow",
    atuNumber: "ATU 57",
    category: "Animal Tales",
    emoji: "🧀",
    tagline: "A song asked for, a cheese let go, and a compliment seen through.",
    beats: [
      "A crow settles on a branch with a fine piece of cheese",
      "A fox below praises her glossy feathers and wonders aloud how she must sing",
      "The crow opens her beak to sing, and the cheese falls",
      "The fox admits, when asked, that he only wanted the cheese",
      "The crow keeps her song and her dignity, the fox shares the cheese, and both settle down as the light goes gold",
    ],
    signatureElements: [
      "a crow with something worth having",
      "a fox with a smooth tongue",
      "praise that is really a request",
      "a song sung anyway, for its own sake",
    ],
    tone: "knowing, warm, and gently amused",
    exampleOpener:
      "The crow had found the finest piece of cheese in the whole valley, and she meant to enjoy it slowly.",
  },
  {
    id: "the-fox-and-the-grapes",
    label: "The Fox and the Grapes",
    atuNumber: "ATU 59",
    category: "Animal Tales",
    emoji: "🍇",
    tagline: "High grapes, tired legs, and the comfort of letting go.",
    beats: [
      "A fox spots grapes hanging high on a vine and decides they are exactly what he wants",
      "He jumps, and jumps again, and each time falls a little shorter",
      "He rests in the grass and tells himself the grapes were probably sour anyway",
      "A passing friend offers him windfall fruit from the ground, sweet and easy to reach",
      "The fox eats what is near him, watches the vine sway, and grows pleasantly sleepy",
    ],
    signatureElements: [
      "fruit just out of reach",
      "effort that runs out before the goal",
      "a story told to soften a disappointment",
      "something good found lower down",
    ],
    tone: "rueful, kind, and unhurried",
    exampleOpener:
      "The grapes hung so high that the fox had to tip his head all the way back to see them, which is a very good way to get dizzy.",
  },
  {
    id: "the-fox-and-the-crane",
    label: "The Fox and the Crane",
    atuNumber: "ATU 60",
    category: "Animal Tales",
    emoji: "🍽️",
    tagline: "Two dinners, two wrong dishes, and a friendship that survives them.",
    beats: [
      "A fox invites a crane to supper and serves the soup in a wide flat dish",
      "The crane's long beak clicks against the plate and she goes home hungry",
      "The crane returns the invitation and serves the meal in a tall narrow jar",
      "The fox's broad nose will not fit, and he understands at last how it felt",
      "The two of them make a third supper together, in dishes that suit them both, and eat it slowly by the fire",
    ],
    signatureElements: [
      "a host who has not thought it through",
      "a guest too polite to say so",
      "the same lesson served twice",
      "a meal finally shared properly",
    ],
    tone: "comic, fair-minded, and finally cosy",
    exampleOpener:
      "The fox meant well, which is not quite the same as thinking ahead.",
  },
  {
    id: "more-timid-than-the-hare",
    label: "More Timid Than the Hare",
    atuNumber: "ATU 70",
    category: "Animal Tales",
    emoji: "🐇",
    tagline: "Hares who think they are the most frightened creatures alive, until they meet the frogs.",
    beats: [
      "The hares decide they are the most easily startled animals in the world",
      "They set off together for the pond, downhearted about it",
      "As they arrive, every frog on the bank leaps into the water at the sight of them",
      "The hares realise they have startled someone, and are astonished",
      "They go home the long way, sitting up straighter, and sleep with their ears relaxed",
    ],
    signatureElements: [
      "a group convinced of their own smallness",
      "a solemn expedition",
      "frogs scattering at a shadow",
      "a discovery that changes how you walk",
    ],
    tone: "tender, funny, and quietly encouraging",
    exampleOpener:
      "There is nothing so heavy as a hare who has decided, first thing in the morning, that he is a coward.",
  },
  {
    id: "the-wolf-and-the-crane",
    label: "The Wolf and the Crane",
    atuNumber: "ATU 76",
    category: "Animal Tales",
    emoji: "🕊️",
    tagline: "A bone in a throat, a long beak, and a wage never paid.",
    beats: [
      "A wolf gets something stuck in his throat and cannot shift it",
      "He promises a rich reward to anyone who will reach in and pull it out",
      "A crane puts in her long neck and lifts the thing free",
      "The wolf says the reward was letting her take her head back out again",
      "The crane laughs at him, keeps her own counsel, and flies home to a nest full of quiet",
    ],
    signatureElements: [
      "a predicament that needs a smaller helper",
      "a promise made in difficulty",
      "a reward redefined afterwards",
      "a helper who does not need thanking",
    ],
    tone: "dry, level, and unbothered",
    exampleOpener:
      "The wolf could not swallow, could not speak, and could not, most annoyingly, ask nicely.",
  },
  {
    id: "the-vain-little-stag",
    label: "The Vain Little Stag",
    atuNumber: "ATU 77",
    category: "Animal Tales",
    emoji: "🦌",
    tagline: "Beautiful antlers, unremarkable legs, and which of them turns out to matter.",
    beats: [
      "A stag admires his branching antlers in a still pool and is very pleased",
      "He looks down at his thin legs and wishes they were finer",
      "A noise in the woods sends him running, and it is his legs that carry him clear",
      "His antlers catch in a thicket, and a friend patiently helps him free",
      "He drinks at the pool again in the evening, fond of all four legs, and lies down among the ferns",
    ],
    signatureElements: [
      "a reflection admired too long",
      "the showy part and the useful part",
      "branches that catch where legs did not",
      "a truce with one's own body",
    ],
    tone: "gently self-aware and softly resolved",
    exampleOpener:
      "The pool was so still that the stag could count every point of his antlers, and he counted them more than once.",
  },
  {
    id: "the-mouse-the-bird-and-the-sausage",
    label: "The Mouse, the Bird, and the Sausage",
    atuNumber: "ATU 85",
    category: "Animal Tales",
    emoji: "🐭",
    tagline: "Three housemates, three jobs, and what happens when they swap.",
    beats: [
      "A mouse, a bird and a sausage keep house together, each with a task that suits them",
      "The bird decides the division is unfair and insists they all swap",
      "Nothing goes right: every one of them is hopeless at somebody else's work",
      "They sit down in the mess and admit they liked things as they were",
      "The old jobs go back where they belong, supper is late but good, and the little house grows quiet",
    ],
    signatureElements: [
      "an oddly assorted household",
      "work that fits the worker",
      "a swap that teaches by going wrong",
      "a familiar routine, gratefully resumed",
    ],
    tone: "domestic, funny, and comfortable",
    exampleOpener:
      "It was a very small house, and it held a mouse, a bird, a sausage, and no arguments at all — for a while.",
  },
  {
    id: "the-cat-and-the-fox",
    label: "The Cat and the Fox",
    atuNumber: "ATU 105",
    category: "Animal Tales",
    emoji: "🐱",
    tagline: "A hundred ways to escape, one way that works.",
    beats: [
      "A fox boasts of the hundred stratagems he keeps in his bag",
      "A cat admits she knows only one",
      "Something comes crashing through the undergrowth toward them",
      "The cat is up the tree before the fox has finished choosing among his hundred",
      "The fox joins her on a low branch, they watch the moon come up together, and neither mentions it again",
    ],
    signatureElements: [
      "a boaster with a long list",
      "a friend with one good skill",
      "a moment that needs a decision now",
      "a branch big enough for two",
    ],
    tone: "brisk, funny, and companionable",
    exampleOpener:
      "'A hundred,' said the fox, 'and every one of them excellent.' The cat said nothing, which was, as it turned out, her whole method.",
  },
  {
    id: "belling-the-cat",
    label: "Belling the Cat",
    atuNumber: "ATU 110",
    category: "Animal Tales",
    emoji: "🔔",
    tagline: "A brilliant plan, and the small matter of who will carry it out.",
    beats: [
      "The mice hold a meeting about the cat and her very quiet feet",
      "A young mouse proposes a bell on a ribbon, and the room applauds",
      "An old mouse asks the obvious question: who will tie it on?",
      "Nobody volunteers, and the plan is set down gently rather than shouted about",
      "They agree instead to listen better and warn one another, and go home to bed pleased with themselves",
    ],
    signatureElements: [
      "a council of small creatures",
      "an idea everyone loves",
      "one question nobody has asked",
      "a humbler plan that actually works",
    ],
    tone: "wry, communal, and sensible",
    exampleOpener:
      "The mice met at midnight, as mice do, and the meeting went beautifully right up until it did not.",
  },
  {
    id: "town-mouse-and-country-mouse",
    label: "Town Mouse and Country Mouse",
    atuNumber: "ATU 112",
    category: "Animal Tales",
    emoji: "🏙️",
    tagline: "A rich table with interruptions, and a plain one with peace.",
    beats: [
      "A town mouse visits the country and finds the supper very plain",
      "He invites his cousin back to the town to show her what eating really means",
      "The town spread is magnificent, and twice it has to be abandoned in a hurry",
      "The country mouse says she would rather have beans in quiet than cake in alarm",
      "She goes home to her own small hole, and sleeps the whole night through without once running",
    ],
    signatureElements: [
      "two cousins and two ideas of plenty",
      "a splendid table",
      "meals interrupted",
      "a plain supper eaten all the way to the end",
    ],
    tone: "warm, comparative, and finally restful",
    exampleOpener:
      "The country mouse set out her best: a bean, a crust, and a very small piece of cheese, arranged with great care.",
  },
  {
    id: "the-three-little-pigs",
    label: "The Three Little Pigs",
    atuNumber: "ATU 124",
    category: "Animal Tales",
    emoji: "🐷",
    tagline: "Straw, sticks, bricks, and a huffing visitor who is mostly out of breath.",
    beats: [
      "Three young pigs set out to build houses of their own",
      "Straw goes up fast, sticks a little slower, and bricks slowest of all",
      "A wolf comes huffing and puffing, and two houses come apart in the wind",
      "All three pigs gather safe behind the brick walls while the wolf runs out of breath",
      "The wolf sits down, admits he is tired and lonely, is given soup at the door, and everyone goes to bed warm",
    ],
    signatureElements: [
      "three houses and three kinds of hurry",
      "a wolf with strong lungs and poor manners",
      "a door that holds",
      "room made at the table for the one outside",
    ],
    tone: "bouncy, rhythmic, and finally hospitable",
    exampleOpener:
      "The first little pig built his house in an afternoon and was very pleased with himself by teatime.",
  },
  {
    id: "how-dogs-and-cats-became-rivals",
    label: "How Dogs and Cats Became Rivals",
    atuNumber: "ATU 200",
    category: "Animal Tales",
    emoji: "🐕",
    tagline: "A lost paper, a misplaced trust, and why one of them still watches the other.",
    beats: [
      "A dog and a cat are given a paper that settles an old question between them",
      "The dog asks the cat to keep it somewhere safe",
      "The paper is tucked into a rafter and, over a long winter, quietly nibbled by mice",
      "Neither can produce it, so neither can win, and the argument has nowhere to go",
      "They agree to disagree, curl at opposite ends of the same warm hearth, and sleep",
    ],
    signatureElements: [
      "a document that settles everything",
      "a safe place that is not safe",
      "mice with no interest in the argument",
      "two old rivals sharing a fire",
    ],
    tone: "mock-solemn and finally companionable",
    exampleOpener:
      "Long ago the matter was written down, signed, and put somewhere extremely sensible.",
  },
  {
    id: "the-election-of-the-bird-king",
    label: "The Election of the Bird-King",
    atuNumber: "ATU 221",
    category: "Animal Tales",
    emoji: "🐦",
    tagline: "Whoever flies highest shall be king — and a very small bird has been thinking.",
    beats: [
      "The birds decide their king shall be whoever can fly the highest",
      "The eagle climbs and climbs until the others are specks below him",
      "A tiny wren, tucked in the eagle's feathers, hops out and flutters a hand's breadth higher",
      "The birds argue, then laugh, and decide cleverness counts for something too",
      "They crown the wren for a day and the eagle for a day, and all roost together as the sky turns violet",
    ],
    signatureElements: [
      "a contest with clear rules",
      "a great bird doing a great thing",
      "a small passenger nobody noticed",
      "a compromise everyone can live with",
    ],
    tone: "bright, comic, and generous",
    exampleOpener:
      "Every bird in the world came, which made the meadow very loud and the meeting very long.",
  },
  {
    id: "the-geese-and-the-last-prayer",
    label: "The Geese and the Last Prayer",
    atuNumber: "ATU 227",
    category: "Animal Tales",
    emoji: "🪿",
    tagline: "A flock with one more thing to say, and a story with no end in sight.",
    beats: [
      "A flock of geese is gathered by the water at evening",
      "Each goose has one last thing to say before settling",
      "So the first goose says hers, and then the next, and then the next",
      "The telling goes round the flock, quieter and slower each time",
      "The story cannot finish while a goose remains, and by then every listener is asleep",
    ],
    signatureElements: [
      "a flock at the water's edge",
      "one more thing, and one more",
      "a rhythm that will not resolve",
      "sleep arriving before the ending does",
    ],
    tone: "circular, hypnotic, and deliberately endless",
    exampleOpener:
      "There were more geese on the water than anyone had ever counted, and every single one of them had something to say.",
  },
  {
    id: "the-fox-and-the-crayfish",
    label: "The Fox and the Crayfish",
    atuNumber: "ATU 275",
    category: "Animal Tales",
    emoji: "🦀",
    tagline: "A race against someone who has thought about it more carefully.",
    beats: [
      "A fox challenges a crayfish to a race, certain of the outcome",
      "The crayfish agrees and quietly takes hold of the fox's tail",
      "The fox runs magnificently, all the way to the finish, and turns to look back",
      "The crayfish lets go and is already there behind him",
      "The fox laughs at himself, carries the crayfish back to the water, and the river goes silver in the dusk",
    ],
    signatureElements: [
      "a race nobody should lose",
      "a competitor with a plan",
      "a tail put to unexpected use",
      "a good loser and a ride home",
    ],
    tone: "playful, sly, and good-natured",
    exampleOpener:
      "'A race,' said the fox, 'between me and you,' and he laughed so hard he did not feel the small weight fasten on behind.",
  },
  {
    id: "the-wind-and-the-sun",
    label: "The Wind and the Sun",
    atuNumber: "ATU 298",
    category: "Animal Tales",
    emoji: "☀️",
    tagline: "Two forces argue about strength, and a traveller's coat decides it.",
    beats: [
      "The wind and the sun argue about which of them is stronger",
      "They agree the winner is whoever can get the coat off a traveller below",
      "The wind blows harder and harder, and the traveller only wraps himself tighter",
      "The sun comes out gently and warms the road until the coat comes off by itself",
      "The wind concedes, the traveller lies down in a warm field, and the afternoon goes still",
    ],
    signatureElements: [
      "a contest between force and warmth",
      "a coat held close",
      "gentleness succeeding where strength failed",
      "a warm road and a nap",
    ],
    tone: "calm, allegorical, and deeply soothing",
    exampleOpener:
      "The wind said he was the stronger, and said it loudly, which is very much the wind's way of arguing.",
  },
  {
    id: "the-twelve-dancing-princesses",
    label: "The Twelve Dancing Princesses",
    atuNumber: "ATU 306",
    category: "Tales of Magic",
    emoji: "👠",
    tagline: "Twelve pairs of worn-through shoes, and a secret staircase under the floor.",
    beats: [
      "Every morning, twelve sisters' dancing shoes are found worn quite through",
      "Nobody can explain it, and the sisters only smile",
      "A kind gardener is lent a cloak that makes him quiet as dust, and follows them",
      "Down a stair beneath the floor lies a silver wood, a lake, and a hall full of music",
      "He asks instead of telling, is invited to dance, and the whole company drifts home at dawn to sleep till noon",
    ],
    signatureElements: [
      "shoes danced to pieces every night",
      "a trapdoor under a bed",
      "a wood of silver and a still lake",
      "a secret shared rather than exposed",
    ],
    tone: "glimmering, secretive, and dreamlike",
    exampleOpener:
      "Nobody could say how it happened, but every single morning the twelve pairs of little shoes had holes worn right through the soles.",
  },
  {
    id: "rapunzel",
    label: "Rapunzel",
    atuNumber: "ATU 310",
    category: "Tales of Magic",
    emoji: "🌷",
    tagline: "A tower, a long golden braid, and a window that finally opens.",
    beats: [
      "A girl with hair like a river of light lives high in a tower with one round window",
      "She lets her braid down for the only visitor she knows, and sings to pass the days",
      "A traveller hears the singing from far off and comes back evening after evening to listen",
      "Between them they work out how the window might open, and it takes patience, not daring",
      "She comes down into the long grass, sees the stars from underneath for the first time, and sleeps under them",
    ],
    signatureElements: [
      "a tower with a single window",
      "hair long enough to reach the ground",
      "a song carrying across the trees",
      "a way out found slowly and together",
    ],
    tone: "yearning, patient, and finally spacious",
    exampleOpener:
      "From the top of the tower you could see three rivers, and Rapunzel had named all of them herself.",
  },
  {
    id: "the-magic-flight",
    label: "The Magic Flight",
    atuNumber: "ATU 313",
    category: "Tales of Magic",
    emoji: "🪄",
    tagline: "A comb, a mirror, a hairbrush — and each one becomes a whole landscape.",
    beats: [
      "Two friends set out for home with three small ordinary things in a pocket",
      "Someone is following, and the road behind them is getting shorter",
      "The comb is thrown down and becomes a forest of tall dark trees",
      "The mirror becomes a wide calm lake, and the brush a range of rolling hills",
      "By the time the hills have risen the follower has given up, and the two walk the last mile in soft evening light",
    ],
    signatureElements: [
      "small objects with enormous consequences",
      "a pursuit that stays off the page",
      "a landscape unfolding behind you",
      "a last mile walked slowly",
    ],
    tone: "rushing at first, then wide and calm",
    exampleOpener:
      "They had three things in their pocket: a comb, a mirror, and a hairbrush. It did not seem like very much.",
  },
  {
    id: "jack-and-the-beanstalk",
    label: "Jack and the Beanstalk",
    atuNumber: "ATU 328",
    category: "Tales of Magic",
    emoji: "🌱",
    tagline: "Five odd beans, a vine into the clouds, and a household in the sky.",
    beats: [
      "Jack trades the family cow for a handful of beans and is sent to bed without supper",
      "By morning a green vine has grown clean through the clouds",
      "He climbs all day and finds a house up there, far too big, with an enormous sleepy owner",
      "A harp that plays itself and a hen with golden eggs are offered, not taken, once Jack asks properly",
      "He climbs down with a gift and a promise to visit, and the beanstalk sways him gently to sleep",
    ],
    signatureElements: [
      "beans that are worth more than they look",
      "a vine into the clouds",
      "a giant household on a giant scale",
      "something given rather than carried off",
    ],
    tone: "wondering, tall, and finally hospitable",
    exampleOpener:
      "They were not even very impressive beans — five of them, greyish, rattling around in the bottom of his pocket.",
  },
  {
    id: "the-animal-bride",
    label: "The Animal Bride",
    atuNumber: "ATU 402",
    category: "Tales of Magic",
    emoji: "🐭",
    tagline: "A companion who is not what they seem, and a friend who waits to find out.",
    beats: [
      "A traveller meets a creature who speaks kindly and asks for company",
      "They keep house together, and the creature is wiser and gentler than expected",
      "One night the traveller glimpses something that explains everything",
      "Instead of demanding answers, the traveller simply stays, and keeps staying",
      "The enchantment loosens on its own, quietly, and the two of them sit up late talking until the fire burns low",
    ],
    signatureElements: [
      "a companion under an enchantment",
      "a household that works better than it should",
      "a secret glimpsed by accident",
      "patience rather than a demand",
    ],
    tone: "gentle, curious, and unhurried",
    exampleOpener:
      "The creature at the door said 'good evening' so politely that it seemed rude to be surprised.",
  },
  {
    id: "east-of-the-sun-west-of-the-moon",
    label: "East of the Sun and West of the Moon",
    atuNumber: "ATU 425A",
    category: "Tales of Magic",
    emoji: "🌗",
    tagline: "A journey past the edge of every map, with the winds for company.",
    beats: [
      "A traveller must reach a place that lies east of the sun and west of the moon",
      "No road goes there, so she asks the winds, one after another",
      "The East Wind carries her a long way and hands her to the West",
      "The North Wind, oldest and strongest, gathers all his breath for the final journey",
      "She arrives as the sky turns pale, finds what she was looking for, and sleeps a whole day and night",
    ],
    signatureElements: [
      "a destination with no road",
      "four winds, each older than the last",
      "a journey measured in exhaustion",
      "arrival at the pale hour before dawn",
    ],
    tone: "epic, wind-blown, and finally still",
    exampleOpener:
      "Nobody could tell her the way, because the way was east of the sun and west of the moon, which is not a direction you can point at.",
  },
  {
    id: "rumpelstiltskin",
    label: "Rumpelstiltskin",
    atuNumber: "ATU 500",
    category: "Tales of Magic",
    emoji: "🧵",
    tagline: "Straw spun to gold, an impossible bargain, and a name overheard in a wood.",
    beats: [
      "A girl is left in a room of straw and told to spin it into gold by morning",
      "A small odd helper appears and does it for her, three nights running, for a promise",
      "The promise turns out to cost far more than she meant to give",
      "She is granted three days to guess his name, and hears it sung by a fire deep in the wood",
      "She says the name, the little man laughs, releases her from the bargain, and goes off into the trees whistling",
    ],
    signatureElements: [
      "a room full of straw",
      "a helper with a price",
      "a name that is the whole puzzle",
      "a bargain undone by listening",
    ],
    tone: "tense, then relieved and oddly fond",
    exampleOpener:
      "The room was full of straw right up to the rafters, and the door had already been locked.",
  },
  {
    id: "the-three-spinners",
    label: "The Three Spinners",
    atuNumber: "ATU 501",
    category: "Tales of Magic",
    emoji: "🧶",
    tagline: "Three strange helpers at the door, and a debt paid in kindness.",
    beats: [
      "A girl is set a heap of flax to spin and no idea how to begin",
      "Three old women appear at the door, each shaped oddly by a lifetime of spinning",
      "They will do the work if they are invited to the feast and introduced as her aunts",
      "She keeps her word gladly, and the whole hall is told exactly who they are",
      "The spinners are honoured, the spinning is finished, and everyone sits down to a long, contented supper",
    ],
    signatureElements: [
      "an impossible heap of flax",
      "three helpers marked by their work",
      "a promise about how they will be treated",
      "a promise kept in public",
    ],
    tone: "warm, fair, and quietly proud",
    exampleOpener:
      "The flax filled the room to the windowsills, and the girl sat down beside it and thought about crying.",
  },
  {
    id: "one-eye-two-eyes-three-eyes",
    label: "One-Eye, Two-Eyes, and Three-Eyes",
    atuNumber: "ATU 511",
    category: "Tales of Magic",
    emoji: "🌳",
    tagline: "A sister who is different, a goat who helps, and a tree only she can pick from.",
    beats: [
      "Three sisters, and the middle one is left out for being ordinary",
      "A gentle goat teaches her a rhyme that lays a full table",
      "Her sisters watch, and learn, and the table stops coming",
      "A silver tree grows where the goat rested, and its fruit will only come to her hand",
      "She shares the fruit anyway, the sisters sit down with her at last, and the evening is quiet",
    ],
    signatureElements: [
      "a sister singled out for being different",
      "a helpful animal and a small rhyme",
      "a tree that answers to one person",
      "sharing offered instead of withheld",
    ],
    tone: "lonely at first, then warm and reconciled",
    exampleOpener:
      "Two-Eyes was the odd one out, which she thought was very unfair, since two eyes are what most people have.",
  },
  {
    id: "the-extraordinary-companions",
    label: "The Extraordinary Companions",
    atuNumber: "ATU 513",
    category: "Tales of Magic",
    emoji: "💪",
    tagline: "Six friends with six impossible talents, and a task that needs all of them.",
    beats: [
      "A traveller gathers companions, each with one wildly specific gift",
      "One can run faster than sight, one hear the grass grow, one drink a river",
      "A task is set that no single person could manage",
      "Each companion's odd talent turns out to be exactly the one needed, in turn",
      "They divide what they have earned six ways and fall asleep round the same fire",
    ],
    signatureElements: [
      "a company assembled one by one",
      "talents that seem useless alone",
      "a task that needs every one of them",
      "a fire with six sleepers round it",
    ],
    tone: "rollicking, generous, and companionable",
    exampleOpener:
      "The first one he met could run so fast he had to tie one leg up just to walk.",
  },
  {
    id: "the-golden-bird",
    label: "The Golden Bird",
    atuNumber: "ATU 550",
    category: "Tales of Magic",
    emoji: "🪶",
    tagline: "A feather of light, a long road, and a helper who keeps giving good advice.",
    beats: [
      "A single glowing feather sets a young traveller off on a search",
      "A fox meets him on the road and gives advice that is always right and never obvious",
      "Twice he forgets the advice, and twice it costs him time rather than harm",
      "The third time he listens, and the golden bird comes willingly to his hand",
      "He rides home with the fox trotting alongside, and the bird sings them both to sleep",
    ],
    signatureElements: [
      "a feather that will not stop glowing",
      "an advisor who is easy to ignore",
      "mistakes that cost time, not blood",
      "a bird that comes when asked properly",
    ],
    tone: "questing, patient, and softly luminous",
    exampleOpener:
      "The feather lay in the garden path giving off a light of its own, which is not something a feather ought to do.",
  },
  {
    id: "the-water-of-life",
    label: "The Water of Life",
    atuNumber: "ATU 551",
    category: "Tales of Magic",
    emoji: "💧",
    tagline: "A long search for the one thing that will make someone well again.",
    beats: [
      "A parent is ill, and only water from a far-off spring will help",
      "Three travellers set out; two take the quick road and get stuck in it",
      "The youngest stops to help everyone who asks, and is slowed down by all of them",
      "Each person helped turns out to know one piece of the way",
      "The water is brought home in time, the household breathes out, and the whole family sleeps properly for the first time in weeks",
    ],
    signatureElements: [
      "a journey undertaken for someone else",
      "a shortcut that is not one",
      "kindnesses that turn into directions",
      "a household finally able to rest",
    ],
    tone: "urgent, kind, and deeply relieved",
    exampleOpener:
      "The spring was said to be eleven days away, and they had rather less than eleven days.",
  },
  {
    id: "the-fisherman-and-his-wife",
    label: "The Fisherman and His Wife",
    atuNumber: "ATU 555",
    category: "Tales of Magic",
    emoji: "🐟",
    tagline: "A wish-granting fish, a growing list, and the quiet of asking for nothing.",
    beats: [
      "A fisherman catches a fish that speaks, and lets it go without asking for anything",
      "At home he is sent back to ask for a cottage, and the fish grants it",
      "The asking grows: a house, then a hall, then more than anyone could use",
      "Standing at the water's edge with the biggest wish yet, he finds he cannot say it",
      "They keep the cottage, put the list away, and sit outside it watching the sea go dark",
    ],
    signatureElements: [
      "a fish that talks",
      "a wish granted too easily",
      "a list that keeps growing",
      "a wish left unspoken at the water's edge",
    ],
    tone: "escalating, then hushed and grateful",
    exampleOpener:
      "The fish looked up at him out of the net and said, quite clearly, 'I would rather you didn't.'",
  },
  {
    id: "the-magic-ring",
    label: "The Magic Ring",
    atuNumber: "ATU 560",
    category: "Tales of Magic",
    emoji: "💍",
    tagline: "A ring that grants help, lost and found by the friends who were paying attention.",
    beats: [
      "A traveller is given a ring that brings help whenever it is truly needed",
      "It is used well, and life becomes easy and then careless",
      "The ring is lost, and everything easy stops being easy",
      "A cat and a dog who were never thanked go looking for it and bring it back",
      "It is worn on a string thereafter and used rarely, and the three of them nap in the sun",
    ],
    signatureElements: [
      "a ring that answers a real need",
      "help that becomes a habit",
      "two animals nobody credited",
      "a treasure recovered and used sparingly",
    ],
    tone: "cautionary and finally affectionate",
    exampleOpener:
      "The ring was plain, and warm, and slightly too big, and it did exactly what you needed on the days you truly needed it.",
  },
  {
    id: "aladdin",
    label: "Aladdin",
    atuNumber: "ATU 561",
    category: "Tales of Magic",
    emoji: "🪔",
    tagline: "A lamp in a cave, a helper made of smoke, and a wish worth making.",
    beats: [
      "A boy is sent down into a cave for a lamp that looks like nothing at all",
      "Rubbed clean, it lets out an enormous helper made of smoke and lamplight",
      "Palaces and gardens arrive faster than anyone can enjoy them",
      "When the lamp goes missing, it is friends, not magic, who help him through",
      "His last wish sets the helper free, and the two of them watch the stars come out over the rooftops",
    ],
    signatureElements: [
      "a plain lamp in a dark place",
      "a helper too large for the room",
      "wonders arriving faster than they can be enjoyed",
      "a final wish spent on someone else",
    ],
    tone: "glittering, generous, and finally still",
    exampleOpener:
      "The lamp was so dull and so dented that Aladdin nearly left it behind on the cave floor.",
  },
  {
    id: "the-wishing-table",
    label: "The Wishing-Table",
    atuNumber: "ATU 563",
    category: "Tales of Magic",
    emoji: "🍽️",
    tagline: "A table that lays itself, and the friends who gather round it.",
    beats: [
      "A traveller is given a small folding table that lays itself with supper",
      "Word gets round, and the table feeds more and more people each evening",
      "One night the table is swapped for an ordinary one while he sleeps",
      "The people he had fed notice at once and put it right without being asked",
      "The table is set up in the square for good, and the village eats together and drifts home yawning",
    ],
    signatureElements: [
      "a table that needs no cook",
      "word spreading through a village",
      "a swap noticed by the right people",
      "a shared supper under the stars",
    ],
    tone: "abundant, communal, and heart-warming",
    exampleOpener:
      "'Table, be set,' he said, feeling extremely silly, and the table was set.",
  },
  {
    id: "the-magic-porridge-pot",
    label: "The Magic Porridge Pot",
    atuNumber: "ATU 565",
    category: "Tales of Magic",
    emoji: "🍲",
    tagline: "A pot that cooks on command, and a village learning the word for stop.",
    beats: [
      "A little pot is given that cooks sweet porridge at a word",
      "The word works beautifully, and the household eats well for the first time in months",
      "One day the pot is started and nobody present remembers the stopping word",
      "Porridge fills the kitchen, the street, and most of the village",
      "The word is remembered at last, everyone eats their way tidily home, and the village sleeps very full indeed",
    ],
    signatureElements: [
      "a small pot with a big appetite",
      "two words, one remembered and one not",
      "porridge going gently everywhere",
      "a village fed to a standstill",
    ],
    tone: "escalating, absurd, and delicious",
    exampleOpener:
      "'Cook, little pot, cook,' she said, and it did, and that was the easy half of the arrangement.",
  },
  {
    id: "the-rabbit-herd",
    label: "The Rabbit Herd",
    atuNumber: "ATU 570",
    category: "Tales of Magic",
    emoji: "🐰",
    tagline: "An impossible job — keep a hundred rabbits together — and a whistle that does it.",
    beats: [
      "A traveller is set the impossible task of herding a hundred rabbits",
      "The rabbits go in a hundred directions before he has finished counting them",
      "A small whistle is given to him by someone he was kind to",
      "One note brings every rabbit back, ears up, from every corner of the kingdom",
      "The task is finished, the rabbits are let loose in a clover field, and everyone dozes in the long grass",
    ],
    signatureElements: [
      "a task designed to be impossible",
      "a hundred rabbits going a hundred ways",
      "a whistle earned by kindness",
      "a clover field at the end of it",
    ],
    tone: "chaotic, then triumphant and drowsy",
    exampleOpener:
      "A hundred rabbits, he was told, and not one of them to be missing by evening.",
  },
  {
    id: "the-golden-goose",
    label: "The Golden Goose",
    atuNumber: "ATU 571",
    category: "Tales of Magic",
    emoji: "🪿",
    tagline: "A goose of gold, and everyone who touches it stuck fast in a growing parade.",
    beats: [
      "A kind young traveller shares his small lunch and is given a golden goose",
      "Someone reaches out to take a feather and finds they cannot let go",
      "One by one a whole procession attaches itself, each stuck to the last",
      "The parade winds through the town, more absurd at every corner",
      "Somebody watching laughs for the first time in years, the goose lets everyone go, and the town has supper together",
    ],
    signatureElements: [
      "a lunch shared with a stranger",
      "a goose nobody can let go of",
      "a procession getting longer",
      "laughter that unsticks everything",
    ],
    tone: "silly, snowballing, and joyful",
    exampleOpener:
      "The goose was solid gold, warm to hold, and — this became clear quite quickly — extremely difficult to put down.",
  },
  {
    id: "spindle-shuttle-and-needle",
    label: "Spindle, Shuttle, and Needle",
    atuNumber: "ATU 585",
    category: "Tales of Magic",
    emoji: "🪡",
    tagline: "Three tools left behind, and the road they make all by themselves.",
    beats: [
      "A girl alone in a small cottage has three things: a spindle, a shuttle, and a needle",
      "She works with them quietly and keeps the house in order",
      "A traveller passes by and does not stop, and she wishes he had",
      "The spindle unrolls a golden thread down the road, the shuttle weaves a carpet, the needle dresses the room",
      "He follows the thread back, finds her house glowing and welcoming, and stays for supper and a long talk",
    ],
    signatureElements: [
      "three ordinary tools",
      "a house kept quietly in order",
      "a golden thread rolling down a road",
      "a room that makes itself welcoming",
    ],
    tone: "quiet, industrious, and softly magical",
    exampleOpener:
      "She had three things in the whole world, and she kept all three of them shining.",
  },
  {
    id: "the-princess-and-the-pea",
    label: "The Princess and the Pea",
    atuNumber: "ATU 704",
    category: "Tales of Magic",
    emoji: "🫛",
    tagline: "Twenty mattresses, one small pea, and a very poor night's sleep.",
    beats: [
      "A traveller arrives at the door on a rainy night asking for a bed",
      "A pea is slipped under the mattress, and then nineteen more mattresses are piled on top",
      "She climbs all the way up and lies there, and lies there, and does not sleep a wink",
      "In the morning she says, apologetically, that something small was in the way",
      "The pea is removed, the mattresses come down to a sensible two, and she sleeps until the afternoon",
    ],
    signatureElements: [
      "a stormy night and an unexpected guest",
      "one pea and twenty mattresses",
      "a night spent entirely awake",
      "a sensible bed at last",
    ],
    tone: "absurd, cosy, and extremely sleepy",
    exampleOpener:
      "It was raining the sort of rain that gets into your shoes, and somebody was knocking at the door.",
  },
  {
    id: "the-clever-peasant-girl",
    label: "The Clever Peasant Girl",
    atuNumber: "ATU 875",
    category: "Realistic Tales",
    emoji: "🧠",
    tagline: "Impossible riddles, answered by someone nobody expected to answer them.",
    beats: [
      "A ruler sets riddles that nobody at court can untangle",
      "A farmer's daughter hears them repeated in the market and answers under her breath",
      "She is brought in, and answers each one plainly and without showing off",
      "Asked to come neither walking nor riding, she arrives in a way nobody had thought of",
      "She is offered a seat at the council table, takes it, and everyone goes home to bed thoughtful",
    ],
    signatureElements: [
      "riddles that stump the clever",
      "an answer from an unexpected corner",
      "conditions met in an unexpected way",
      "a seat offered and taken",
    ],
    tone: "sharp, satisfying, and quietly triumphant",
    exampleOpener:
      "The riddle had been read aloud in the square nine times, and nine times the crowd had gone quiet.",
  },
  {
    id: "king-thrushbeard",
    label: "King Thrushbeard",
    atuNumber: "ATU 900",
    category: "Realistic Tales",
    emoji: "🎻",
    tagline: "A sharp tongue, a plain year, and a friendship built on level ground.",
    beats: [
      "Someone very proud dismisses everyone who comes to the door, with a joke for each",
      "One of those dismissed suggests, mildly, that she try a year of ordinary work",
      "She learns to sell pots, to sweep, to mend, and finds she is not bad at it",
      "She meets the same person again and recognises them, and this time they talk properly",
      "The two of them sit on the step at the end of a working day, tired and companionable, and watch the light go",
    ],
    signatureElements: [
      "a sharp tongue and a long list of refusals",
      "a year of ordinary work",
      "skills learned from the beginning",
      "a conversation between equals",
    ],
    tone: "humbling, warm, and evenly balanced",
    exampleOpener:
      "She had a joke ready for every single one of them, and she used them all before lunchtime.",
  },
  {
    id: "loving-like-salt",
    label: "Loving Like Salt",
    atuNumber: "ATU 923",
    category: "Realistic Tales",
    emoji: "🧂",
    tagline: "A daughter's odd answer about love, and a supper with no salt in it.",
    beats: [
      "A father asks his daughters how much they love him",
      "The youngest says 'as much as salt', and is misunderstood entirely",
      "She goes away and works quietly in another household for a long while",
      "She sends back a feast prepared with no salt at all, and every dish tastes of nothing",
      "He understands at last, they sit down to a properly seasoned supper together, and neither says much",
    ],
    signatureElements: [
      "a question about love",
      "an answer that sounds like an insult",
      "a feast that tastes of nothing",
      "an understanding that needs no speech",
    ],
    tone: "quiet, aching, and warmly resolved",
    exampleOpener:
      "'As much as salt,' said the youngest, and her father put down his cup.",
  },
  {
    id: "lucky-hans",
    label: "Lucky Hans",
    atuNumber: "ATU 1415",
    category: "Anecdotes and Jokes",
    emoji: "🍀",
    tagline: "A trade, and a trade, and a trade, and a man who ends up with nothing and is delighted.",
    beats: [
      "Hans finishes seven years of work and is paid with a lump of gold as big as his head",
      "It is heavy, so he trades it for a horse, which is fast, so he trades it for a cow",
      "The cow becomes a pig, the pig a goose, the goose a grindstone",
      "The grindstone rolls into a pond, and Hans finds he is carrying nothing at all",
      "He walks home with empty hands and a light heart and sleeps the whole way through the afternoon",
    ],
    signatureElements: [
      "a fortune too heavy to carry",
      "a chain of cheerful bad bargains",
      "a stone in a pond",
      "empty hands and no regrets",
    ],
    tone: "artless, sunny, and enormously restful",
    exampleOpener:
      "The lump of gold was as big as Hans's head, and after an hour on the road it felt considerably bigger.",
  },
  {
    id: "castles-in-the-air",
    label: "Castles in the Air",
    atuNumber: "ATU 1430",
    category: "Anecdotes and Jokes",
    emoji: "🏰",
    tagline: "Two daydreamers, one pot of milk, and a fortune spent before it arrives.",
    beats: [
      "Two friends carry a pot of milk to market and start planning what to buy",
      "The milk becomes a cow, the cow a herd, the herd a house with a red door",
      "They furnish the house, name the garden, and argue about where the gate should go",
      "A gesture in the middle of the argument tips the pot into the road",
      "They look at the spilled milk, laugh at themselves, and walk home planning something smaller and much more likely",
    ],
    signatureElements: [
      "a pot of milk and a long walk",
      "a fortune built one step at a time",
      "an argument about an imaginary gate",
      "a plan cut down to size",
    ],
    tone: "dreamy, funny, and fondly deflating",
    exampleOpener:
      "It was only a pot of milk, but by the time they reached the crossroads it was very nearly an estate.",
  },
  {
    id: "stone-soup",
    label: "Stone Soup",
    atuNumber: "ATU 1548",
    category: "Anecdotes and Jokes",
    emoji: "🥣",
    tagline: "A stone, a big pot, and a village that turns out to have plenty after all.",
    beats: [
      "A traveller with nothing arrives in a village where every door stays shut",
      "She fills a great pot with water, drops in a smooth stone, and starts to stir",
      "Someone asks what she is making, and is told stone soup — wonderful, though a carrot would lift it",
      "A carrot arrives, then an onion, then barley, then a handful of herbs from three different gardens",
      "The whole village eats together in the square, the stone is washed and pocketed, and everyone goes home full",
    ],
    signatureElements: [
      "a stone at the bottom of the pot",
      "doors that open one at a time",
      "an ingredient from every house",
      "a square full of people eating",
    ],
    tone: "canny, generous, and glowing",
    exampleOpener:
      "She set the pot down in the middle of the square, dropped in a smooth grey stone, and began, quite seriously, to stir.",
  },
  {
    id: "the-goat-who-wouldnt-go-home",
    label: "The Goat Who Wouldn't Go Home",
    atuNumber: "ATU 2015",
    category: "Formula Tales",
    emoji: "🐐",
    tagline: "A goat who will not budge, and everyone in turn asked to help.",
    beats: [
      "A goat plants herself in the garden and will not go home",
      "The dog is asked to move the goat, and declines",
      "The stick is asked to move the dog, the fire the stick, the water the fire",
      "Each one refuses in turn, and the chain grows longer and more elaborate",
      "At last one small creature agrees, the whole chain unlocks backwards, and the goat ambles home to bed",
    ],
    signatureElements: [
      "a goat entirely at rest",
      "a chain of polite refusals",
      "a rhythm that builds with each link",
      "the smallest helper unlocking it all",
    ],
    tone: "cumulative, rhythmic, and lulling",
    exampleOpener:
      "The goat was in the cabbages, and the goat was not coming out, and the goat had made this very clear.",
  },
  {
    id: "the-old-woman-and-her-pig",
    label: "The Old Woman and Her Pig",
    atuNumber: "ATU 2030",
    category: "Formula Tales",
    emoji: "🐖",
    tagline: "A pig that will not cross the stile, and a chain of favours that finally moves.",
    beats: [
      "An old woman buys a pig, and the pig will not go over the stile",
      "She asks the dog, then the stick, then the fire, then the water, and each one says no",
      "The chain of asking grows longer, each request repeated in full",
      "Somewhere near the end, one creature agrees, for a small consideration",
      "Everything unlocks backwards down the whole chain, the pig goes over the stile, and they are home before dark",
    ],
    signatureElements: [
      "a pig at a standstill",
      "a request repeated in full each time",
      "a chain that must run to the end",
      "everything unlocking backwards at once",
    ],
    tone: "patterned, patient, and hypnotic",
    exampleOpener:
      "She had a silver sixpence, and she bought a pig, and that was where the easy part stopped.",
  },
  {
    id: "stronger-and-strongest",
    label: "Stronger and Strongest",
    atuNumber: "ATU 2031",
    category: "Formula Tales",
    emoji: "🧱",
    tagline: "Who is the strongest thing in the world? Everyone has a better answer.",
    beats: [
      "Someone sets out to find the strongest thing in the world",
      "The sun seems strongest, until a cloud covers it",
      "The cloud gives way to the wind, and the wind is stopped by a wall",
      "The wall is worn away by a mouse, and the mouse is watched by a cat",
      "The chain comes round to something very small and ordinary, and the search ends in a warm kitchen",
    ],
    signatureElements: [
      "a question with no final answer",
      "each mightiest thing overturned by the next",
      "a chain that circles back",
      "an ending in the ordinary",
    ],
    tone: "circular, philosophical, and comforting",
    exampleOpener:
      "The sun, obviously, was the strongest thing in the world — until a small cloud went across it.",
  },
  {
    id: "the-house-that-jack-built",
    label: "The House That Jack Built",
    atuNumber: "ATU 2035",
    category: "Formula Tales",
    emoji: "🏠",
    tagline: "A house, a malt, a rat, a cat — and every verse carries all the ones before.",
    beats: [
      "This is the house that Jack built, and that is the whole of the first verse",
      "Each new verse adds one thing and then recites everything that came before it",
      "The chain lengthens: the malt, the rat, the cat, the dog, the cow with the crumpled horn",
      "The reciting takes longer and longer and the voice gets slower and slower",
      "By the last verse it is barely above a whisper, and the house is dark and quiet",
    ],
    signatureElements: [
      "one house at the start of everything",
      "a verse that grows by one each time",
      "the whole chain recited every round",
      "a whisper by the end",
    ],
    tone: "incantatory, slowing, and made for falling asleep to",
    exampleOpener:
      "This is the house that Jack built. That is all, for now. There will be more in a moment.",
  },
  {
    id: "the-enormous-turnip",
    label: "The Enormous Turnip",
    atuNumber: "ATU 2044",
    category: "Formula Tales",
    emoji: "🥬",
    tagline: "A turnip too big to pull, and everyone in the house holding on behind.",
    beats: [
      "A turnip grows until it is bigger than the wheelbarrow",
      "One person pulls, and pulls, and it does not move",
      "The household joins on one at a time, each holding the one in front",
      "The very smallest creature takes hold at the back, and out it comes all at once",
      "Everyone lands in a heap, laughing, and there is turnip soup for a week",
    ],
    signatureElements: [
      "a vegetable of unreasonable size",
      "a line of people all pulling",
      "the smallest one making the difference",
      "a heap of laughing helpers",
    ],
    tone: "rhythmic, communal, and joyful",
    exampleOpener:
      "It had been an ordinary turnip in the spring. By autumn you could not see over the top of it.",
  },
  {
    id: "the-endless-tale",
    label: "The Endless Tale",
    atuNumber: "ATU 2300",
    category: "Formula Tales",
    emoji: "♾️",
    tagline: "A tale with no ending at all, as the sheep go over the wall one at a time.",
    beats: [
      "A storyteller begins a tale about a very great number of sheep",
      "The sheep must cross a wall, and they can only go over one at a time",
      "So one sheep goes over. And then one sheep goes over. And then one sheep goes over",
      "Anyone who asks what happens next is told that the sheep are still going over",
      "The telling continues, softer and slower, for exactly as long as anyone is awake to hear it",
    ],
    signatureElements: [
      "an impossibly large flock",
      "a wall crossed one sheep at a time",
      "a story that refuses to advance",
      "a telling that outlasts the listener",
    ],
    tone: "deliberately monotonous, soft, and endless",
    exampleOpener:
      "There were a hundred thousand sheep, and a wall, and a gap in the wall exactly one sheep wide.",
  },
];
