"""Alembic environment.

Schema changes are hand-written SQL, not autogenerated: this is an
ingest-and-read-only-API shape where SQL *is* the model, and there is no ORM
metadata to diff against (assessment §6.6).
"""

from __future__ import annotations

from alembic import context
from sqlalchemy import create_engine

from atukb.config import settings

config = context.config


def _sqlalchemy_url() -> str:
    """SQLAlchemy needs the driver named; psycopg3 is not psycopg2."""
    dsn = settings.dsn
    if dsn.startswith("postgresql://"):
        return dsn.replace("postgresql://", "postgresql+psycopg://", 1)
    return dsn


def run_migrations_offline() -> None:
    context.configure(url=_sqlalchemy_url(), literal_binds=True)
    with context.begin_transaction():
        context.run_migrations()


def run_migrations_online() -> None:
    engine = create_engine(_sqlalchemy_url(), future=True)
    with engine.connect() as connection:
        context.configure(connection=connection)
        with context.begin_transaction():
            context.run_migrations()


if context.is_offline_mode():
    run_migrations_offline()
else:
    run_migrations_online()
