/**
 * Step 1 of growing the catalogue: work out which ATU tale types are even
 * worth asking about.
 *
 * Reads the knowledge base's license-filtered export, drops everything the
 * catalogue already carries by hand, and runs the deterministic screen in
 * `lib/safety.ts` over each canonical scholarly title. What survives is a
 * *candidate* — not an entry. Nothing here decides that a tale type is
 * suitable; it decides only that it is not obviously unsuitable, which is a
 * much weaker and much cheaper claim.
 *
 * The rejects are written out alongside the candidates, with the term that
 * caught each one, so the screen can be argued with rather than trusted.
 *
 * Run with:  npm run catalogue:propose
 */

import { readFileSync, writeFileSync, existsSync, mkdirSync } from "node:fs";
import { resolve, dirname } from "node:path";
import { unsafeTermsIn } from "../lib/safety.ts";

const REPO_ROOT = resolve(import.meta.dirname, "..");
const EXPORT_PATH = resolve(
  process.env.ATUKB_EXPORT_DIR ?? resolve(REPO_ROOT, "kb/export"),
  "tale-types.jsonl",
);
const OUTPUT_PATH = resolve(REPO_ROOT, "data/atu-candidates.json");

interface ExportedTaleType {
  code: string;
  division: string | null;
  preferred_title: string | null;
  preferred_title_source: string | null;
  title_disputed: boolean;
  spdx: string | null;
  code_kind: string;
}

export interface Candidate {
  atu: string;
  canonicalTitle: string;
  division: string;
  source: string;
  spdx: string;
  disputed: boolean;
}

/** ATU numbers already in the hand-authored catalogue, which we never re-propose. */
function existingCodes(): Set<string> {
  const codes = new Set<string>();
  const index = readFileSync(resolve(REPO_ROOT, "lib/atu-index.ts"), "utf8");
  for (const m of index.matchAll(/\batu: "([^"]+)"/g)) codes.add(m[1]);
  const featured = readFileSync(resolve(REPO_ROOT, "lib/tale-types.ts"), "utf8");
  for (const m of featured.matchAll(/\batuNumber: "ATU\s+([^"]+)"/g)) codes.add(m[1]);
  return codes;
}

function main(): number {
  if (!existsSync(EXPORT_PATH)) {
    console.error(
      `propose-catalogue: no export at ${EXPORT_PATH}.\n` +
        `Run \`cd kb && atukb publish && atukb export\` first.`,
    );
    return 1;
  }

  const existing = existingCodes();
  const byCode = new Map<string, ExportedTaleType>();

  for (const line of readFileSync(EXPORT_PATH, "utf8").split("\n")) {
    if (!line.trim()) continue;
    const row = JSON.parse(line) as ExportedTaleType;
    if (!row.preferred_title) continue;
    // A code can appear more than once across editions and sources; the first
    // titled row wins, which matches what `sync-atu-index.ts` already does.
    if (!byCode.has(row.code)) byCode.set(row.code, row);
  }

  const candidates: Candidate[] = [];
  const rejected: Array<Candidate & { terms: string[] }> = [];
  let skippedExisting = 0;
  let skippedRange = 0;

  for (const [code, row] of byCode) {
    if (existing.has(code)) {
      skippedExisting++;
      continue;
    }
    // The app maps a bare number to a division by numeric range; a code it
    // cannot parse would land in the wrong section of the catalogue.
    if (!/^\d/.test(code)) {
      skippedRange++;
      continue;
    }

    const entry: Candidate = {
      atu: code,
      canonicalTitle: row.preferred_title!,
      division: row.division ?? "unknown",
      source: row.preferred_title_source ?? "unknown",
      spdx: row.spdx ?? "NOASSERTION",
      disputed: row.title_disputed,
    };

    const terms = unsafeTermsIn(entry.canonicalTitle);
    if (terms.length) rejected.push({ ...entry, terms });
    else candidates.push(entry);
  }

  candidates.sort((a, b) => a.atu.localeCompare(b.atu, "en", { numeric: true }));
  rejected.sort((a, b) => a.atu.localeCompare(b.atu, "en", { numeric: true }));

  mkdirSync(dirname(OUTPUT_PATH), { recursive: true });
  writeFileSync(
    OUTPUT_PATH,
    JSON.stringify(
      {
        note:
          "Generated by `npm run catalogue:propose`. Candidates are tale types " +
          "the deterministic screen in lib/safety.ts did not reject on their " +
          "canonical title alone. They are NOT yet catalogue entries — " +
          "`npm run catalogue:draft` still has to judge each one.",
        generatedFrom: "kb/export/tale-types.jsonl",
        counts: {
          inExport: byCode.size,
          alreadyInCatalogue: skippedExisting,
          unparseableCode: skippedRange,
          candidates: candidates.length,
          rejectedByScreen: rejected.length,
        },
        candidates,
        rejected,
      },
      null,
      2,
    ) + "\n",
    "utf8",
  );

  console.log(
    `propose-catalogue: ${byCode.size} titled tale types in the export\n` +
      `  ${skippedExisting} already hand-authored in the catalogue\n` +
      `  ${skippedRange} with a code the app cannot place by range\n` +
      `  ${rejected.length} rejected by the deterministic screen\n` +
      `  ${candidates.length} candidates written to ${OUTPUT_PATH}`,
  );
  return 0;
}

process.exit(main());
